// Generated by scripts/generate-pgi-native-schemas.mjs.
// Source: Pocket-Genes-Catalog-Wiki/schemas/protocol/pgi*.schema.json
// Do not edit this file by hand.

export const PGI_NATIVE_SCHEMAS = {
  "mdm": {
    "title": "PGI1 MDMAPIModel",
    "description": ".pgi1.json native provider payload matching the app MDMAPIModel Codable contract.",
    "$ref": "#/$defs/MDMAPIModel",
    "$defs": {
      "MDMAPIModel": {
        "type": "object",
        "properties": {
          "panels": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/PanelAPIModel"
            },
            "minItems": 0
          },
          "pharmacos": {
            "$ref": "#/$defs/PharmageneticAPIModel"
          },
          "pathology": {
            "$ref": "#/$defs/PathologyAPIModel"
          },
          "ancestry": {
            "$ref": "#/$defs/AncestryAPIModel"
          },
          "variants": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/VariantAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "panels",
          "pharmacos",
          "pathology",
          "ancestry",
          "variants"
        ],
        "additionalProperties": false
      },
      "PanelAPIModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "background_image": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "categories": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/CategoryAPIModel"
                },
                "minItems": 0
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "id",
          "name",
          "description"
        ],
        "additionalProperties": false
      },
      "CategoryAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "category_icon": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "genome": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/GenomeAPIModel"
                },
                "minItems": 0
              },
              {
                "type": "null"
              }
            ]
          },
          "ideal_gen_percentage": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "GenomeAPIModel": {
        "type": "object",
        "properties": {
          "gen": {
            "type": "string"
          },
          "snp": {
            "type": "string"
          },
          "ideal_gen": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "my_gen": {
            "type": "string"
          }
        },
        "required": [
          "gen",
          "snp",
          "my_gen"
        ],
        "additionalProperties": false
      },
      "PharmageneticAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/PharmageneticCategoryAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "name",
          "description",
          "categories"
        ],
        "additionalProperties": false
      },
      "PharmageneticCategoryAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "sf_icon": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "types": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/DrugCategoryAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "name",
          "types"
        ],
        "additionalProperties": false
      },
      "DrugCategoryAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "sf_icon": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "drugs": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/DrugsLevelAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "name",
          "drugs"
        ],
        "additionalProperties": false
      },
      "DrugsLevelAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "risk": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "low",
                  "medium",
                  "high",
                  "veryHigh"
                ]
              },
              {
                "type": "null"
              }
            ]
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "analyzed_genes": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/DrugGenAPIModel"
            },
            "minItems": 0
          },
          "result": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "name",
          "analyzed_genes"
        ],
        "additionalProperties": false
      },
      "DrugGenAPIModel": {
        "type": "object",
        "properties": {
          "gen": {
            "type": "string"
          },
          "genotype": {
            "type": "string"
          },
          "effect": {
            "type": "string"
          },
          "conclusion": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "gen",
          "genotype",
          "effect"
        ],
        "additionalProperties": false
      },
      "PathologyAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/PathologyCategory"
            },
            "minItems": 0
          }
        },
        "required": [
          "name",
          "description",
          "categories"
        ],
        "additionalProperties": false
      },
      "PathologyCategory": {
        "type": "object",
        "properties": {
          "category_icon": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "conditions": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/ConditionAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "category_icon",
          "name",
          "conditions"
        ],
        "additionalProperties": false
      },
      "ConditionAPIModel": {
        "type": "object",
        "properties": {
          "condition": {
            "type": "string"
          },
          "is_genetic_variant": {
            "type": "boolean"
          },
          "gen_variant": {
            "anyOf": [
              {
                "$ref": "#/$defs/GenVariantAPIModel"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "condition",
          "is_genetic_variant"
        ],
        "additionalProperties": false
      },
      "GenVariantAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          },
          "condition": {
            "type": "string"
          },
          "explanation": {
            "type": "string"
          },
          "gen_info": {
            "$ref": "#/$defs/GenVariantInfoAPIModel"
          }
        },
        "required": [
          "title",
          "icon",
          "condition",
          "explanation",
          "gen_info"
        ],
        "additionalProperties": false
      },
      "GenVariantInfoAPIModel": {
        "type": "object",
        "properties": {
          "gen": {
            "type": "string"
          },
          "nm": {
            "type": "string"
          },
          "c_dna": {
            "type": "string"
          },
          "protein": {
            "type": "string"
          },
          "cigosity": {
            "type": "string"
          },
          "depth": {
            "type": "string"
          },
          "snv": {
            "type": "string"
          },
          "classification": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "variant_description": {
            "type": "string"
          }
        },
        "required": [
          "gen",
          "nm",
          "c_dna",
          "protein",
          "cigosity",
          "depth",
          "snv",
          "classification",
          "description",
          "variant_description"
        ],
        "additionalProperties": false
      },
      "AncestryAPIModel": {
        "type": "object",
        "properties": {
          "charts": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/AncestryChartAPIModel"
            },
            "minItems": 0
          },
          "lineage": {
            "$ref": "#/$defs/LineageAPIModel"
          },
          "world_map": {
            "$ref": "#/$defs/WorldMapAPIModel"
          }
        },
        "required": [
          "charts",
          "lineage",
          "world_map"
        ],
        "additionalProperties": false
      },
      "AncestryChartAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "percentage": {
            "type": "number"
          },
          "color": {
            "type": "string"
          },
          "sub_sectors": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "$ref": "#/$defs/AncestryChartAPIModel"
                },
                "minItems": 0
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "name",
          "percentage",
          "color"
        ],
        "additionalProperties": false
      },
      "LineageAPIModel": {
        "type": "object",
        "properties": {
          "paternal_lineage": {
            "$ref": "#/$defs/LineageDetailsAPIModel"
          },
          "maternal_lineage": {
            "$ref": "#/$defs/LineageDetailsAPIModel"
          }
        },
        "required": [
          "paternal_lineage",
          "maternal_lineage"
        ],
        "additionalProperties": false
      },
      "LineageDetailsAPIModel": {
        "type": "object",
        "properties": {
          "haplogroup": {
            "$ref": "#/$defs/LineageInfoAPIModel"
          },
          "migration": {
            "$ref": "#/$defs/LineageInfoAPIModel"
          },
          "history": {
            "$ref": "#/$defs/LineageInfoAPIModel"
          }
        },
        "required": [
          "haplogroup",
          "migration",
          "history"
        ],
        "additionalProperties": false
      },
      "LineageInfoAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "desription": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "desription"
        ],
        "additionalProperties": false
      },
      "WorldMapAPIModel": {
        "type": "object",
        "properties": {
          "image_url": {
            "type": "string"
          },
          "genetic_distribution": {
            "type": "string"
          },
          "lineage": {
            "type": "string"
          },
          "halogroups": {
            "type": "string"
          },
          "limitations": {
            "type": "string"
          },
          "more_info": {
            "$ref": "#/$defs/MoreInfoAPIModel"
          }
        },
        "required": [
          "image_url",
          "genetic_distribution",
          "lineage",
          "halogroups",
          "limitations",
          "more_info"
        ],
        "additionalProperties": false
      },
      "MoreInfoAPIModel": {
        "type": "object",
        "properties": {
          "explanation": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "explanation",
          "description"
        ],
        "additionalProperties": false
      },
      "VariantAPIModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "chrom": {
            "type": "string"
          },
          "position": {
            "type": "integer"
          },
          "reference": {
            "type": "string"
          },
          "alternate": {
            "type": "string"
          },
          "quality": {
            "type": "number"
          },
          "info": {
            "type": "string"
          },
          "filter": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "chrom",
          "position",
          "reference",
          "alternate",
          "quality",
          "info",
          "filter"
        ],
        "additionalProperties": false
      }
    }
  },
  "ag": {
    "title": "PGI2 AGAPIModel",
    "description": ".pgi2.json native provider payload matching the app AGAPIModel Codable contract.",
    "$ref": "#/$defs/AGAPIModel",
    "$defs": {
      "AGAPIModel": {
        "type": "object",
        "properties": {
          "variants": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/VariantAPIModel"
            },
            "minItems": 0
          },
          "result": {
            "$ref": "#/$defs/ResultAPIModel"
          },
          "resume": {
            "$ref": "#/$defs/ResumeAPIModel"
          },
          "information": {
            "$ref": "#/$defs/InformationAPIModel"
          },
          "panel_information": {
            "$ref": "#/$defs/PanelInfoAPIModel"
          },
          "genomic_methods": {
            "$ref": "#/$defs/GenomicMethodsAPIModel"
          },
          "methodological_limitations": {
            "$ref": "#/$defs/MethodologyLimitationsAPIModel"
          },
          "disclaimer": {
            "$ref": "#/$defs/DisclaimerAPIModel"
          },
          "sequenced_regions": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/SequencedGenAPIModel"
            },
            "minItems": 0
          },
          "sequence": {
            "$ref": "#/$defs/SequenceAPIModel"
          },
          "genetic_counseling": {
            "$ref": "#/$defs/GeneticCounselingAPIModel"
          },
          "variant_interpretations": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/VariantInterpretationAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "variants",
          "result",
          "resume",
          "information",
          "panel_information",
          "genomic_methods",
          "methodological_limitations",
          "disclaimer",
          "sequenced_regions",
          "sequence",
          "genetic_counseling",
          "variant_interpretations"
        ],
        "additionalProperties": false
      },
      "VariantAPIModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "chrom": {
            "type": "string"
          },
          "position": {
            "type": "integer"
          },
          "reference": {
            "type": "string"
          },
          "alternate": {
            "type": "string"
          },
          "quality": {
            "type": "number"
          },
          "info": {
            "type": "string"
          },
          "filter": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "chrom",
          "position",
          "reference",
          "alternate",
          "quality",
          "info",
          "filter"
        ],
        "additionalProperties": false
      },
      "ResultAPIModel": {
        "type": "object",
        "properties": {
          "cards": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/TitleDescriptionAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "cards"
        ],
        "additionalProperties": false
      },
      "TitleDescriptionAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description"
        ],
        "additionalProperties": false
      },
      "ResumeAPIModel": {
        "type": "object",
        "properties": {
          "prioritized_genetic_variants": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/GeneticVariantAPIModel"
            },
            "minItems": 0
          },
          "copy_number_variants": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/GeneticVariantAPIModel"
            },
            "minItems": 0
          },
          "other_identified_genetic_variants": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/GeneticVariantAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "prioritized_genetic_variants",
          "copy_number_variants",
          "other_identified_genetic_variants"
        ],
        "additionalProperties": false
      },
      "GeneticVariantAPIModel": {
        "type": "object",
        "properties": {
          "variant_number": {
            "type": "integer"
          },
          "gene": {
            "type": "string"
          },
          "hg39_position": {
            "type": "string"
          },
          "variant": {
            "type": "string"
          },
          "zygosity": {
            "type": "string"
          },
          "classification": {
            "type": "string"
          },
          "condition": {
            "type": "string"
          }
        },
        "required": [
          "variant_number",
          "gene",
          "hg39_position",
          "variant",
          "zygosity",
          "classification",
          "condition"
        ],
        "additionalProperties": false
      },
      "InformationAPIModel": {
        "type": "object",
        "properties": {
          "case_information": {
            "$ref": "#/$defs/CaseInfoAPIModel"
          },
          "medical_information": {
            "$ref": "#/$defs/MedicalInfo"
          },
          "patient_information": {
            "$ref": "#/$defs/PatientInfoAPIModel"
          },
          "references": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/ReferenceAPIModel"
            },
            "minItems": 0
          },
          "clinical_diagnosis": {
            "type": "string"
          },
          "hpo_terms": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/HpoTermAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "case_information",
          "medical_information",
          "patient_information",
          "references",
          "clinical_diagnosis",
          "hpo_terms"
        ],
        "additionalProperties": false
      },
      "CaseInfoAPIModel": {
        "type": "object",
        "properties": {
          "case_id": {
            "type": "string"
          },
          "sample_id": {
            "type": "string"
          },
          "sample_type": {
            "type": "string"
          },
          "cnvs": {
            "type": "boolean"
          },
          "mtdna": {
            "type": "boolean"
          },
          "reception_date": {
            "type": "string"
          },
          "sequencing_date": {
            "type": "string"
          },
          "report_date": {
            "type": "string"
          }
        },
        "required": [
          "case_id",
          "sample_id",
          "sample_type",
          "cnvs",
          "mtdna",
          "reception_date",
          "sequencing_date",
          "report_date"
        ],
        "additionalProperties": false
      },
      "MedicalInfo": {
        "type": "object",
        "properties": {
          "doctor_name": {
            "type": "string"
          },
          "clinic": {
            "type": "string"
          },
          "lab": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "required": [
          "doctor_name",
          "clinic",
          "lab",
          "email"
        ],
        "additionalProperties": false
      },
      "PatientInfoAPIModel": {
        "type": "object",
        "properties": {
          "patient_name": {
            "type": "string"
          },
          "dni_ci": {
            "type": "string"
          },
          "sex": {
            "type": "string"
          },
          "birth_date": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "legal_guardian": {
            "type": "string"
          }
        },
        "required": [
          "patient_name",
          "dni_ci",
          "sex",
          "birth_date",
          "age",
          "legal_guardian"
        ],
        "additionalProperties": false
      },
      "ReferenceAPIModel": {
        "type": "object",
        "properties": {
          "sample_id": {
            "type": "string"
          },
          "relation": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          }
        },
        "required": [
          "sample_id",
          "relation",
          "full_name"
        ],
        "additionalProperties": false
      },
      "HpoTermAPIModel": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "hpo_id": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "hpo_id"
        ],
        "additionalProperties": false
      },
      "PanelInfoAPIModel": {
        "type": "object",
        "properties": {
          "a_vision_info": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "regions_info": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "mitocondrial_sequence": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "cover_diseases": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "panel_content": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          }
        },
        "required": [
          "a_vision_info",
          "regions_info",
          "mitocondrial_sequence",
          "cover_diseases",
          "panel_content"
        ],
        "additionalProperties": false
      },
      "GenomicMethodsAPIModel": {
        "type": "object",
        "properties": {
          "extraction_and_sequencing": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "bioinformatic_processing": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "databases_used": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "variant_interpretation": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "results_categorization": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          }
        },
        "required": [
          "extraction_and_sequencing",
          "bioinformatic_processing",
          "databases_used",
          "variant_interpretation",
          "results_categorization"
        ],
        "additionalProperties": false
      },
      "MethodologyLimitationsAPIModel": {
        "type": "object",
        "properties": {
          "limited_coverage": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "interpretation_errors": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "structural_variants": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "public_databases": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "unknown_variants": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "test_errors": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          },
          "evolving_evidence": {
            "$ref": "#/$defs/TitleDescriptionAPIModel"
          }
        },
        "required": [
          "limited_coverage",
          "interpretation_errors",
          "structural_variants",
          "public_databases",
          "unknown_variants",
          "test_errors",
          "evolving_evidence"
        ],
        "additionalProperties": false
      },
      "DisclaimerAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description"
        ],
        "additionalProperties": false
      },
      "SequencedGenAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "analyzed_genes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          },
          "color": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description",
          "analyzed_genes",
          "color"
        ],
        "additionalProperties": false
      },
      "SequenceAPIModel": {
        "type": "object",
        "properties": {
          "laboratory": {
            "type": "string"
          },
          "genomic_library": {
            "type": "string"
          },
          "sequencing_platform": {
            "type": "string"
          },
          "expected_mean_coverage": {
            "type": "string"
          },
          "protocol": {
            "type": "string"
          },
          "samples": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/SampleCoverageAPIModel"
            },
            "minItems": 0
          }
        },
        "required": [
          "laboratory",
          "genomic_library",
          "sequencing_platform",
          "expected_mean_coverage",
          "protocol",
          "samples"
        ],
        "additionalProperties": false
      },
      "SampleCoverageAPIModel": {
        "type": "object",
        "properties": {
          "relation": {
            "type": "string"
          },
          "sample_id": {
            "type": "string"
          },
          "quality": {
            "type": "string"
          },
          "mean_coverage": {
            "type": "integer"
          },
          "coverage_over_20x": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          }
        },
        "required": [
          "relation",
          "sample_id",
          "quality",
          "mean_coverage",
          "coverage_over_20x",
          "icon"
        ],
        "additionalProperties": false
      },
      "GeneticCounselingAPIModel": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description"
        ],
        "additionalProperties": false
      },
      "VariantInterpretationAPIModel": {
        "type": "object",
        "properties": {
          "variant_number": {
            "type": "integer"
          },
          "variant_name": {
            "type": "string"
          },
          "acmg_classification": {
            "type": "string"
          },
          "associated_phenotypes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          },
          "variant_details": {
            "$ref": "#/$defs/VariantDetails"
          },
          "post_analysis": {
            "$ref": "#/$defs/PostAnalysis"
          },
          "quality_metrics": {
            "$ref": "#/$defs/QualityMetrics"
          },
          "gnomad": {
            "$ref": "#/$defs/GnomADInfo"
          },
          "functional_prediction": {
            "$ref": "#/$defs/FunctionalPrediction"
          },
          "summary": {
            "type": "string"
          },
          "interpretation": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          }
        },
        "required": [
          "variant_number",
          "variant_name",
          "acmg_classification",
          "associated_phenotypes",
          "variant_details",
          "post_analysis",
          "quality_metrics",
          "gnomad",
          "functional_prediction",
          "summary",
          "interpretation",
          "reference"
        ],
        "additionalProperties": false
      },
      "VariantDetails": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "position": {
            "type": "string"
          },
          "transcripts": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          },
          "exon": {
            "type": "string"
          },
          "total_exons": {
            "type": "string"
          }
        },
        "required": [
          "description",
          "position",
          "transcripts",
          "exon",
          "total_exons"
        ],
        "additionalProperties": false
      },
      "PostAnalysis": {
        "type": "object",
        "properties": {
          "classification": {
            "type": "string"
          },
          "original": {
            "type": "string"
          },
          "criteria": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          }
        },
        "required": [
          "classification",
          "original",
          "criteria"
        ],
        "additionalProperties": false
      },
      "QualityMetrics": {
        "type": "object",
        "properties": {
          "proband": {
            "$ref": "#/$defs/SampleQuality"
          },
          "father": {
            "$ref": "#/$defs/SampleQuality"
          },
          "mother": {
            "$ref": "#/$defs/SampleQuality"
          }
        },
        "required": [
          "proband",
          "father",
          "mother"
        ],
        "additionalProperties": false
      },
      "SampleQuality": {
        "type": "object",
        "properties": {
          "zygosity": {
            "type": "string"
          },
          "quality": {
            "type": "string"
          },
          "depth": {
            "type": "string"
          },
          "allele_fraction": {
            "type": "string"
          }
        },
        "required": [
          "zygosity",
          "quality",
          "depth",
          "allele_fraction"
        ],
        "additionalProperties": false
      },
      "GnomADInfo": {
        "type": "object",
        "properties": {
          "allele_total": {
            "type": "number"
          },
          "allele_count": {
            "type": "integer"
          },
          "allele_max": {
            "type": "number"
          }
        },
        "required": [
          "allele_total",
          "allele_count",
          "allele_max"
        ],
        "additionalProperties": false
      },
      "FunctionalPrediction": {
        "type": "object",
        "properties": {
          "revel": {
            "type": "string"
          },
          "conservation": {
            "type": "string"
          },
          "gerp": {
            "type": "string"
          },
          "phastcons_100_vertebrates": {
            "type": "string"
          },
          "splicing_prediction": {
            "type": "string"
          },
          "spliceai": {
            "type": "string"
          }
        },
        "required": [
          "revel",
          "conservation",
          "gerp",
          "phastcons_100_vertebrates",
          "splicing_prediction",
          "spliceai"
        ],
        "additionalProperties": false
      }
    }
  },
  "2pq": {
    "title": "PGI3 TwoPQAPIModel",
    "description": ".pgi3.json native provider payload matching the app TwoPQAPIModel Codable contract.",
    "$ref": "#/$defs/TwoPQAPIModel",
    "$defs": {
      "TwoPQAPIModel": {
        "type": "object",
        "properties": {
          "main_case": {
            "$ref": "#/$defs/TwoPQMainCaseReference"
          },
          "entities": {
            "$ref": "#/$defs/TwoPQEntities"
          }
        },
        "required": [
          "main_case",
          "entities"
        ],
        "additionalProperties": false
      },
      "TwoPQMainCaseReference": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "sibling_case_ids": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          },
          "parent_batch_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "children_sampling_ids": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          },
          "last_updated": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "id",
          "sibling_case_ids",
          "children_sampling_ids"
        ],
        "additionalProperties": false
      },
      "TwoPQEntities": {
        "type": "object",
        "properties": {
          "batches": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/TwoPQBatch"
            },
            "minItems": 0
          },
          "cases": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/TwoPQCase"
            },
            "minItems": 0
          },
          "samplings": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/TwoPQSampling"
            },
            "minItems": 0
          }
        },
        "required": [
          "batches",
          "cases",
          "samplings"
        ],
        "additionalProperties": false
      },
      "TwoPQBatch": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "const": "batch"
          },
          "scope": {
            "$ref": "#/$defs/TwoPQScope"
          },
          "identity": {
            "$ref": "#/$defs/TwoPQIdentity"
          },
          "status": {
            "$ref": "#/$defs/TwoPQStatus"
          },
          "execution": {
            "$ref": "#/$defs/TwoPQExecution"
          },
          "relations": {
            "$ref": "#/$defs/TwoPQBatchRelations"
          },
          "notes": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "timestamps": {
            "$ref": "#/$defs/TwoPQTimestamps"
          },
          "audit": {
            "$ref": "#/$defs/TwoPQAudit"
          }
        },
        "required": [
          "id",
          "kind",
          "scope",
          "identity",
          "status",
          "execution",
          "relations",
          "timestamps",
          "audit"
        ],
        "additionalProperties": false
      },
      "TwoPQScope": {
        "type": "object",
        "properties": {
          "institutionId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "doctorId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "patientId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQIdentity": {
        "type": "object",
        "properties": {
          "batchLabel": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "runId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "caseLabel": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "sampleId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "caseLabelSnapshot": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQStatus": {
        "type": "object",
        "properties": {
          "analysisStatus": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "caseStatus": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "priority": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "processingStatus": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "qcStatus": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQExecution": {
        "type": "object",
        "properties": {
          "platform": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "scheduling": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "providerName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "providerFormat": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "contactName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "contactEmail": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "phoneNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQBatchRelations": {
        "type": "object",
        "properties": {
          "caseIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          }
        },
        "required": [
          "caseIds"
        ],
        "additionalProperties": false
      },
      "TwoPQTimestamps": {
        "type": "object",
        "properties": {
          "createdAt": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "updatedAt": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQAudit": {
        "type": "object",
        "properties": {
          "createdByEmail": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "updatedByEmail": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQCase": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "const": "case"
          },
          "scope": {
            "$ref": "#/$defs/TwoPQScope"
          },
          "identity": {
            "$ref": "#/$defs/TwoPQIdentity"
          },
          "classification": {
            "$ref": "#/$defs/TwoPQCaseClassification"
          },
          "status": {
            "$ref": "#/$defs/TwoPQStatus"
          },
          "logistics": {
            "$ref": "#/$defs/TwoPQCaseLogistics"
          },
          "relations": {
            "$ref": "#/$defs/TwoPQCaseRelations"
          },
          "notes": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "timestamps": {
            "$ref": "#/$defs/TwoPQTimestamps"
          },
          "audit": {
            "$ref": "#/$defs/TwoPQAudit"
          }
        },
        "required": [
          "id",
          "kind",
          "scope",
          "identity",
          "classification",
          "status",
          "logistics",
          "relations",
          "timestamps",
          "audit"
        ],
        "additionalProperties": false
      },
      "TwoPQCaseClassification": {
        "type": "object",
        "properties": {
          "caseType": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQCaseLogistics": {
        "type": "object",
        "properties": {
          "trackingNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "requestedAt": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "dueAt": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQCaseRelations": {
        "type": "object",
        "properties": {
          "batchId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "samplingIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 0
          }
        },
        "required": [
          "samplingIds"
        ],
        "additionalProperties": false
      },
      "TwoPQSampling": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "const": "sampling"
          },
          "scope": {
            "$ref": "#/$defs/TwoPQScope"
          },
          "identity": {
            "$ref": "#/$defs/TwoPQIdentity"
          },
          "specimen": {
            "$ref": "#/$defs/TwoPQSpecimen"
          },
          "status": {
            "$ref": "#/$defs/TwoPQStatus"
          },
          "dates": {
            "$ref": "#/$defs/TwoPQSamplingDates"
          },
          "relations": {
            "$ref": "#/$defs/TwoPQSamplingRelations"
          },
          "notes": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "timestamps": {
            "$ref": "#/$defs/TwoPQTimestamps"
          },
          "audit": {
            "$ref": "#/$defs/TwoPQAudit"
          }
        },
        "required": [
          "id",
          "kind",
          "scope",
          "identity",
          "specimen",
          "status",
          "dates",
          "relations",
          "timestamps",
          "audit"
        ],
        "additionalProperties": false
      },
      "TwoPQSpecimen": {
        "type": "object",
        "properties": {
          "sampleType": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQSamplingDates": {
        "type": "object",
        "properties": {
          "collectionDate": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "receptionDate": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "runId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      },
      "TwoPQSamplingRelations": {
        "type": "object",
        "properties": {
          "caseId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [],
        "additionalProperties": false
      }
    }
  }
} as const;
