// Generated by scripts/generate-pgo-object-schemas.mjs.
// Source: Pocket-Genes-Catalog-Wiki/schemas/objects/*.schema.json
// Do not edit this file by hand.

export const PGO_OBJECT_SCHEMAS: Readonly<
  Record<string, Record<string, unknown>>
> = {
  "pgo_form": {
    "title": "pgo_form content",
    "type": "object",
    "description": "Minimal domain content for pgo_form.",
    "properties": {
      "form_shape": {
        "type": "object",
        "description": "Frozen form shape.",
        "properties": {
          "fields": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "string",
                  "minLength": 1,
                  "pattern": "^[a-z][a-z0-9_]{0,63}$",
                  "description": "Stable field key.",
                  "maxLength": 64
                },
                "label": {
                  "type": "string",
                  "minLength": 1,
                  "pattern": "\\S",
                  "description": "Human-readable field label.",
                  "maxLength": 120
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "text",
                    "long_text",
                    "email",
                    "phone",
                    "url",
                    "address",
                    "postal_code",
                    "country_code",
                    "identifier",
                    "number",
                    "integer",
                    "positive_integer",
                    "percentage",
                    "boolean",
                    "date",
                    "datetime",
                    "time",
                    "enum",
                    "multi_enum",
                    "string_list",
                    "integer_list",
                    "number_list"
                  ],
                  "description": "Field value and validation type."
                },
                "required": {
                  "type": "boolean",
                  "description": "Whether an answer must be present."
                },
                "options": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 100,
                  "items": {
                    "type": "object",
                    "description": "One enum choice.",
                    "properties": {
                      "value": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$",
                        "maxLength": 128,
                        "description": "Stable stored option value."
                      },
                      "label": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "\\S",
                        "maxLength": 120,
                        "description": "Human-readable option label frozen with the form."
                      }
                    },
                    "required": [
                      "value",
                      "label"
                    ],
                    "additionalProperties": false
                  },
                  "description": "Allowed choices. Present only for enum and multi_enum."
                },
                "help_info_text": {
                  "type": "string",
                  "minLength": 1,
                  "pattern": "\\S",
                  "description": "Optional guidance displayed by the native form.",
                  "maxLength": 500
                }
              },
              "required": [
                "key",
                "label",
                "type",
                "required"
              ],
              "additionalProperties": false,
              "allOf": [
                {
                  "if": {
                    "properties": {
                      "type": {
                        "enum": [
                          "enum",
                          "multi_enum"
                        ]
                      }
                    },
                    "required": [
                      "type"
                    ]
                  },
                  "then": {
                    "required": [
                      "options"
                    ]
                  },
                  "else": {
                    "not": {
                      "required": [
                        "options"
                      ]
                    }
                  }
                }
              ]
            },
            "description": "Ordered frozen field definitions used to render and validate this submission."
          }
        },
        "required": [
          "fields"
        ],
        "additionalProperties": false
      },
      "fields": {
        "type": "array",
        "items": {
          "type": "object",
          "description": "One submitted answer.",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Key of a field declared by form_shape.fields."
            },
            "value": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "number"
                },
                {
                  "type": "boolean"
                },
                {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "number"
                      }
                    ]
                  }
                }
              ],
              "description": "Typed answer validated against the matching frozen field definition."
            }
          },
          "required": [
            "key",
            "value"
          ],
          "additionalProperties": false
        },
        "description": "Submitted answers."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "form_shape",
      "fields"
    ],
    "additionalProperties": false
  },
  "pgo_bundle_of_symptoms": {
    "title": "pgo_bundle_of_symptoms content",
    "type": "object",
    "description": "Minimal domain content for pgo_bundle_of_symptoms.",
    "properties": {
      "observations": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "description": "One symptom observation.",
          "properties": {
            "label": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Readable symptom or observation."
            },
            "presence": {
              "type": "string",
              "enum": [
                "present",
                "absent",
                "uncertain"
              ],
              "description": "Observation presence."
            },
            "code": {
              "type": "object",
              "description": "Optional terminology code.",
              "properties": {
                "system": {
                  "type": "string",
                  "enum": [
                    "hpo",
                    "snomed_ct",
                    "other"
                  ],
                  "description": "Terminology system."
                },
                "value": {
                  "type": "string",
                  "minLength": 1,
                  "pattern": "\\S",
                  "description": "Code in the selected terminology system."
                }
              },
              "required": [
                "system",
                "value"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "label"
          ],
          "additionalProperties": false
        }
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "observations"
    ],
    "additionalProperties": false
  },
  "pgo_bundle_of_candidate_genes": {
    "title": "pgo_bundle_of_candidate_genes content",
    "type": "object",
    "description": "Minimal domain content for pgo_bundle_of_candidate_genes.",
    "properties": {
      "genes": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string",
          "minLength": 1,
          "pattern": "\\S",
          "description": "Gene symbol."
        }
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "genes"
    ],
    "additionalProperties": false
  },
  "pgo_informed_consent": {
    "title": "pgo_informed_consent content",
    "type": "object",
    "description": "Minimal domain content for pgo_informed_consent.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Consent title."
      },
      "text": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual consent text."
      },
      "status": {
        "type": "string",
        "enum": [
          "pending",
          "accepted",
          "declined",
          "withdrawn"
        ],
        "description": "Consent workflow state."
      },
      "accepted_by": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual person who accepted the consent."
      },
      "accepted_at": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual acceptance time.",
        "format": "date-time"
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "text"
    ],
    "additionalProperties": false
  },
  "pgo_test_order": {
    "title": "pgo_test_order content",
    "type": "object",
    "description": "Minimal domain content for pgo_test_order.",
    "properties": {
      "patient": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Patient/source name or meaningful identifier supplied for this order."
      },
      "test_name": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual requested test name."
      },
      "sample_type": {
        "type": "string",
        "enum": [
          "blood",
          "dried_blood_spot",
          "saliva",
          "buccal_swab",
          "tissue",
          "skin_biopsy",
          "bone_marrow_aspirate",
          "bone_marrow_core",
          "amniotic_fluid",
          "chorionic_villi",
          "cord_blood",
          "cerebrospinal_fluid",
          "urine",
          "stool",
          "hair_follicles",
          "nail_clippings",
          "semen",
          "embryo_biopsy",
          "whole_embryo",
          "polar_body",
          "plasma",
          "serum",
          "extracted_dna",
          "extracted_rna",
          "other"
        ],
        "description": "Specimen or material expected by the testing provider.",
        "x-enum-labels": [
          "Blood",
          "Dried blood spot",
          "Saliva",
          "Buccal swab",
          "Tissue",
          "Skin biopsy",
          "Bone marrow aspirate",
          "Bone marrow core biopsy",
          "Amniotic fluid",
          "Chorionic villi",
          "Cord blood",
          "Cerebrospinal fluid",
          "Urine",
          "Stool",
          "Hair follicles",
          "Nail clippings",
          "Semen",
          "Embryo biopsy",
          "Whole embryo",
          "Polar body",
          "Plasma",
          "Serum",
          "Extracted DNA",
          "Extracted RNA",
          "Other"
        ]
      },
      "test_type": {
        "type": "string",
        "enum": [
          "single_gene",
          "gene_panel",
          "exome_sequencing",
          "genome_sequencing",
          "targeted_variant_testing",
          "repeat_expansion_testing",
          "methylation_analysis",
          "chromosomal_microarray",
          "karyotype",
          "fish",
          "other"
        ],
        "description": "Optional broad test category.",
        "x-enum-labels": [
          "Single-gene test",
          "Gene panel",
          "Exome sequencing",
          "Genome sequencing",
          "Targeted variant testing",
          "Repeat expansion testing",
          "Methylation analysis",
          "Chromosomal microarray",
          "Karyotype",
          "FISH",
          "Other"
        ]
      },
      "objective": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Optional objective for the test."
      },
      "clinical_suspicion": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Optional clinical suspicion."
      },
      "genes": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string",
          "minLength": 1,
          "pattern": "\\S",
          "description": "Gene symbol."
        }
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "patient",
      "test_name",
      "sample_type"
    ],
    "additionalProperties": false
  },
  "pgo_collection_request": {
    "title": "pgo_collection_request content",
    "type": "object",
    "description": "Minimal domain content for pgo_collection_request.",
    "properties": {
      "patient": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Patient/source name or meaningful identifier for collection."
      },
      "sample_type": {
        "type": "string",
        "enum": [
          "blood",
          "dried_blood_spot",
          "saliva",
          "buccal_swab",
          "tissue",
          "skin_biopsy",
          "bone_marrow_aspirate",
          "bone_marrow_core",
          "amniotic_fluid",
          "chorionic_villi",
          "cord_blood",
          "cerebrospinal_fluid",
          "urine",
          "stool",
          "hair_follicles",
          "nail_clippings",
          "semen",
          "embryo_biopsy",
          "whole_embryo",
          "polar_body",
          "other"
        ],
        "description": "Biological material to obtain.",
        "x-enum-labels": [
          "Blood",
          "Dried blood spot",
          "Saliva",
          "Buccal swab",
          "Tissue",
          "Skin biopsy",
          "Bone marrow aspirate",
          "Bone marrow core biopsy",
          "Amniotic fluid",
          "Chorionic villi",
          "Cord blood",
          "Cerebrospinal fluid",
          "Urine",
          "Stool",
          "Hair follicles",
          "Nail clippings",
          "Semen",
          "Embryo biopsy",
          "Whole embryo",
          "Polar body",
          "Other"
        ]
      },
      "collection_method": {
        "type": "string",
        "enum": [
          "venous_blood_draw",
          "capillary_blood_collection",
          "buccal_swab",
          "saliva_collection",
          "needle_aspiration",
          "core_biopsy",
          "surgical_biopsy",
          "skin_punch_biopsy",
          "amniocentesis",
          "chorionic_villus_sampling",
          "lumbar_puncture",
          "embryo_biopsy",
          "polar_body_biopsy",
          "self_collection",
          "other"
        ],
        "description": "Method used to obtain the biological material.",
        "x-enum-labels": [
          "Venous blood draw",
          "Capillary blood collection",
          "Buccal swab",
          "Saliva collection",
          "Needle aspiration",
          "Core biopsy",
          "Surgical biopsy",
          "Skin punch biopsy",
          "Amniocentesis",
          "Chorionic villus sampling",
          "Lumbar puncture",
          "Embryo biopsy",
          "Polar body biopsy",
          "Self-collection",
          "Other"
        ]
      },
      "container": {
        "type": "string",
        "enum": [
          "edta_tube",
          "heparin_tube",
          "citrate_tube",
          "serum_tube",
          "dna_stabilization_tube",
          "rna_stabilization_tube",
          "sterile_container",
          "swab_collection_kit",
          "saliva_collection_kit",
          "cryovial",
          "filter_paper_card",
          "formalin_container",
          "other"
        ],
        "description": "Collection container or kit.",
        "x-enum-labels": [
          "EDTA tube",
          "Heparin tube",
          "Citrate tube",
          "Serum tube",
          "DNA stabilization tube",
          "RNA stabilization tube",
          "Sterile container",
          "Swab collection kit",
          "Saliva collection kit",
          "Cryovial",
          "Filter paper card",
          "Formalin container",
          "Other"
        ]
      },
      "requested_quantity": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Readable quantity including its unit, for example 2 mL."
      },
      "collection_site": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Readable collection location."
      },
      "scheduled_at": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Scheduled collection time.",
        "format": "date-time"
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "patient",
      "sample_type"
    ],
    "additionalProperties": false
  },
  "pgo_blood_sample": {
    "title": "pgo_blood_sample content",
    "type": "object",
    "description": "Minimal domain content for pgo_blood_sample.",
    "properties": {
      "sample_label": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual label or identifier used to distinguish the specimen."
      },
      "material": {
        "type": "string",
        "enum": [
          "whole_blood",
          "plasma",
          "serum",
          "buffy_coat",
          "dried_blood_spot",
          "other"
        ],
        "description": "Blood material.",
        "x-enum-labels": [
          "Whole blood",
          "Plasma",
          "Serum",
          "Buffy coat",
          "Dried blood spot",
          "Other"
        ]
      },
      "container": {
        "type": "string",
        "enum": [
          "edta_tube",
          "heparin_tube",
          "citrate_tube",
          "serum_tube",
          "dna_stabilization_tube",
          "rna_stabilization_tube",
          "sterile_container",
          "swab_collection_kit",
          "saliva_collection_kit",
          "cryovial",
          "filter_paper_card",
          "formalin_container",
          "other"
        ],
        "description": "Specimen container.",
        "x-enum-labels": [
          "EDTA tube",
          "Heparin tube",
          "Citrate tube",
          "Serum tube",
          "DNA stabilization tube",
          "RNA stabilization tube",
          "Sterile container",
          "Swab collection kit",
          "Saliva collection kit",
          "Cryovial",
          "Filter paper card",
          "Formalin container",
          "Other"
        ]
      },
      "volume_ml": {
        "type": "number",
        "minimum": 0,
        "description": "Volume in millilitres."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "sample_label"
    ],
    "additionalProperties": false
  },
  "pgo_tissue_sample": {
    "title": "pgo_tissue_sample content",
    "type": "object",
    "description": "Minimal domain content for pgo_tissue_sample.",
    "properties": {
      "sample_label": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual label or identifier used to distinguish the specimen."
      },
      "anatomical_site": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Readable anatomical site."
      },
      "preparation": {
        "type": "string",
        "enum": [
          "fresh",
          "frozen",
          "formalin_fixed_unembedded",
          "ffpe",
          "alcohol_preserved",
          "other"
        ],
        "description": "Tissue preparation.",
        "x-enum-labels": [
          "Fresh",
          "Frozen",
          "Formalin-fixed, unembedded",
          "FFPE",
          "Alcohol-preserved",
          "Other"
        ]
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "sample_label"
    ],
    "additionalProperties": false
  },
  "pgo_embryo_sample": {
    "title": "pgo_embryo_sample content",
    "type": "object",
    "description": "Minimal domain content for pgo_embryo_sample.",
    "properties": {
      "sample_label": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual label or identifier used to distinguish the specimen."
      },
      "material_kind": {
        "type": "string",
        "enum": [
          "embryo_biopsy",
          "whole_embryo",
          "polar_body",
          "other"
        ],
        "description": "Kind of embryo-derived material.",
        "x-enum-labels": [
          "Embryo biopsy",
          "Whole embryo",
          "Polar body",
          "Other"
        ]
      },
      "embryo_identifier": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Associated embryo identifier when known."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "sample_label",
      "material_kind"
    ],
    "additionalProperties": false
  },
  "pgo_dna_sample": {
    "title": "pgo_dna_sample content",
    "type": "object",
    "description": "Minimal domain content for pgo_dna_sample.",
    "properties": {
      "sample_label": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual label or identifier used to distinguish the specimen."
      },
      "volume_ul": {
        "type": "number",
        "minimum": 0,
        "description": "Volume in microlitres."
      },
      "concentration_ng_ul": {
        "type": "number",
        "minimum": 0,
        "description": "Concentration in nanograms per microlitre."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "sample_label"
    ],
    "additionalProperties": false
  },
  "pgo_sequence_reads": {
    "title": "pgo_sequence_reads content",
    "type": "object",
    "description": "Minimal domain content for pgo_sequence_reads.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "reads": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "description": "One downloadable read.",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Unique read key within this object."
            },
            "name": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Readable read name."
            },
            "download_url": {
              "type": "string",
              "minLength": 1,
              "format": "uri",
              "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
              "description": "HTTPS URL used to download this read."
            }
          },
          "required": [
            "key",
            "name",
            "download_url"
          ],
          "additionalProperties": false
        }
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "reads"
    ],
    "additionalProperties": false
  },
  "pgo_sequence_data": {
    "title": "pgo_sequence_data content",
    "type": "object",
    "description": "Minimal domain content for pgo_sequence_data.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_aligned_reads": {
    "title": "pgo_aligned_reads content",
    "type": "object",
    "description": "Minimal domain content for pgo_aligned_reads.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the aligned reads."
      },
      "index_download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the optional alignment index."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_unannotated_vcf": {
    "title": "pgo_unannotated_vcf content",
    "type": "object",
    "description": "Minimal domain content for pgo_unannotated_vcf.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_annotated_vcf": {
    "title": "pgo_annotated_vcf content",
    "type": "object",
    "description": "Minimal domain content for pgo_annotated_vcf.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_interactive_report": {
    "title": "pgo_interactive_report content",
    "type": "object",
    "description": "Minimal domain content for pgo_interactive_report.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_pdf_report": {
    "title": "pgo_pdf_report content",
    "type": "object",
    "description": "Minimal domain content for pgo_pdf_report.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  },
  "pgo_image_bundle": {
    "title": "pgo_image_bundle content",
    "type": "object",
    "description": "Minimal domain content for pgo_image_bundle.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "images": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "description": "One downloadable image.",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Unique image key within this object."
            },
            "name": {
              "type": "string",
              "minLength": 1,
              "pattern": "\\S",
              "description": "Readable image name."
            },
            "download_url": {
              "type": "string",
              "minLength": 1,
              "format": "uri",
              "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
              "description": "HTTPS URL used to download this image."
            }
          },
          "required": [
            "key",
            "name",
            "download_url"
          ],
          "additionalProperties": false
        }
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "images"
    ],
    "additionalProperties": false
  },
  "pgo_karyotype_result": {
    "title": "pgo_karyotype_result content",
    "type": "object",
    "description": "Minimal domain content for pgo_karyotype_result.",
    "properties": {
      "result_notation": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Actual karyotype result notation."
      },
      "interpretation": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Optional readable interpretation."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "result_notation"
    ],
    "additionalProperties": false
  },
  "pgo_flow_cytometry_data": {
    "title": "pgo_flow_cytometry_data content",
    "type": "object",
    "description": "Minimal domain content for pgo_flow_cytometry_data.",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "Human-facing title."
      },
      "download_url": {
        "type": "string",
        "minLength": 1,
        "format": "uri",
        "pattern": "^[Hh][Tt][Tt][Pp][Ss]://[^/?#\\\\\\s]+(?:[/?#]|$)",
        "description": "HTTPS URL used to download the native file."
      },
      "notes": {
        "type": "string",
        "description": "Optional additional information the person wants to communicate. It may be empty."
      }
    },
    "required": [
      "title",
      "download_url"
    ],
    "additionalProperties": false
  }
};
