export type PickerOption = {
  value: string;
  label: string;
};

export type ColorOption = {
  hex: string;
  name: string;
};

export const GENDER_OPTIONS: PickerOption[] = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Other", label: "Other" },
  { value: "Prefer Not To Say", label: "Prefer not to say" },
];

export const CONDITION_OPTIONS: PickerOption[] = [
  "Cystic fibrosis",
  "Sickle cell disease",
  "Beta thalassemia",
  "Alpha thalassemia",
  "G6PD deficiency",
  "Tay-Sachs disease",
  "Gaucher disease",
  "Canavan disease",
  "Niemann-Pick disease",
  "Fabry disease",
  "Pompe disease",
  "MPS I (Hurler syndrome)",
  "MPS II (Hunter syndrome)",
  "MPS III (Sanfilippo syndrome)",
  "PKU (Phenylketonuria)",
  "Maple syrup urine disease",
  "Homocystinuria",
  "MCAD deficiency",
  "LCHAD deficiency",
  "CPT2 deficiency",
  "Wilson disease",
  "Hereditary hemochromatosis",
  "Alpha-1 antitrypsin deficiency",
  "Hereditary breast and ovarian cancer (BRCA1/2)",
  "Lynch syndrome (HNPCC)",
  "Familial hypercholesterolemia",
  "Marfan syndrome",
  "Loeys–Dietz syndrome",
  "Ehlers–Danlos syndrome",
  "Hypertrophic cardiomyopathy",
  "Dilated cardiomyopathy",
  "Long QT syndrome",
  "Brugada syndrome",
  "Catecholaminergic polymorphic ventricular tachycardia",
  "Duchenne muscular dystrophy",
  "Becker muscular dystrophy",
  "Spinal muscular atrophy",
  "Charcot–Marie–Tooth disease",
  "Huntington disease",
  "Fragile X syndrome",
  "Rett syndrome",
  "Tuberous sclerosis complex",
  "Neurofibromatosis type 1",
  "Neurofibromatosis type 2",
  "Von Hippel–Lindau disease",
  "Alport syndrome",
  "Autosomal dominant polycystic kidney disease",
  "Autosomal recessive polycystic kidney disease",
  "Bardet–Biedl syndrome",
  "Usher syndrome",
  "Leber congenital amaurosis",
  "Retinitis pigmentosa",
  "Stargardt disease",
  "Achromatopsia",
  "Oculocutaneous albinism",
  "Congenital hearing loss (GJB2-related)",
  "Hemophilia A",
  "Hemophilia B",
  "Factor V Leiden thrombophilia",
  "Prothrombin G20210A",
  "MTHFR-related thrombophilia",
  "Congenital hypothyroidism",
  "Congenital adrenal hyperplasia",
  "Androgen insensitivity syndrome",
  "22q11.2 deletion syndrome",
  "Down syndrome (trisomy 21)",
  "Edwards syndrome (trisomy 18)",
  "Patau syndrome (trisomy 13)",
  "Prader–Willi syndrome",
  "Angelman syndrome",
  "Williams syndrome",
  "Celiac disease (HLA-associated)",
  "Lactose intolerance (adult hypolactasia)",
  "Familial Mediterranean fever",
  "Hereditary pancreatitis",
  "Hereditary angioedema",
  "Primary ciliary dyskinesia",
  "Hereditary spastic paraplegia",
  "Multiple endocrine neoplasia type 1",
  "Multiple endocrine neoplasia type 2",
  "Mitochondrial encephalomyopathy (MELAS)",
  "Leber hereditary optic neuropathy (LHON)",
  "Other",
].map((value) => ({ value, label: value }));

export const COMMUNITY_CATEGORY_OPTIONS: PickerOption[] = [
  "Ancestry",
  "Medication",
  "Nutrition",
  "Pathologies",
  "Experiences",
  "Education",
  "Research",
].map((value) => ({ value, label: value }));

export const COMMUNITY_ICON_OPTIONS: PickerOption[] = [
  "sparkles",
  "circle.hexagonpath",
  "heart.text.square",
  "bandage",
  "cross.case",
  "stethoscope",
  "pills",
  "book.fill",
  "graduationcap.fill",
  "brain.head.profile",
  "atom",
  "bolt.heart.fill",
  "waveform.path.ecg",
  "flask.fill",
  "leaf.fill",
  "globe.americas.fill",
  "link.circle.fill",
  "lightbulb.fill",
  "chart.bar.fill",
  "person.crop.circle.fill",
  "person.3.fill",
  "star.circle.fill",
  "eye.fill",
  "drop.fill",
  "shield.lefthalf.filled",
  "figure.walk",
  "ear.fill",
  "lungs.fill",
  "testtube.2",
  "staroflife.fill",
].map((value) => ({ value, label: value }));

export const COMMUNITY_COLOR_OPTIONS: ColorOption[] = [
  { name: "Magenta", hex: "#E84393" },
  { name: "Cyan", hex: "#00D2FF" },
  { name: "Coral", hex: "#FF6B6B" },
  { name: "Lime", hex: "#6DDC5F" },
  { name: "Violet", hex: "#7F7CFF" },
  { name: "Amber", hex: "#FFB347" },
  { name: "Blue", hex: "#3A86FF" },
  { name: "Teal", hex: "#2EC4B6" },
  { name: "Mint", hex: "#A8E6CF" },
  { name: "Indigo", hex: "#5A4FCF" },
  { name: "Rose", hex: "#FF5D8F" },
  { name: "Sky", hex: "#74C0FC" },
  { name: "Forest", hex: "#2F9E44" },
  { name: "Gold", hex: "#FFD43B" },
  { name: "Ocean", hex: "#1C7ED6" },
  { name: "Lavender", hex: "#B197FC" },
  { name: "Ruby", hex: "#FA5252" },
  { name: "Slate", hex: "#748FFC" },
  { name: "Emerald", hex: "#20C997" },
  { name: "Peach", hex: "#FFBFA3" },
  { name: "Azure", hex: "#4DABF7" },
  { name: "Plum", hex: "#CC5DE8" },
  { name: "Tangerine", hex: "#FF922B" },
  { name: "Steel", hex: "#A5D8FF" },
  { name: "Neon", hex: "#63E6BE" },
  { name: "Berry", hex: "#F06595" },
  { name: "Sunset", hex: "#FF8787" },
  { name: "Aqua", hex: "#3BC9DB" },
  { name: "Kiwi", hex: "#8CE99A" },
  { name: "Fuchsia", hex: "#E64980" },
  { name: "Cherry", hex: "#C92A2A" },
  { name: "Night", hex: "#364FC7" },
];

const GENERAL_COMMUNITY_TAG_OPTIONS = ["Genomics", "Variants", "Data", "Community"];

const COMMUNITY_TAG_OPTIONS_BY_CATEGORY: Record<string, string[]> = {
  ancestry: ["Haplogroups", "Ethnicity", "Migration", "Family Tree", "Origins"],
  medication: [
    "Pharmacogenomics",
    "Drug Response",
    "Metabolism",
    "Adverse Effects",
    "Dosage",
  ],
  nutrition: [
    "Nutrigenomics",
    "Macros",
    "Micronutrients",
    "Supplements",
    "Diet Plans",
  ],
  pathologies: ["Diagnostics", "Risk", "Carrier", "Hereditary", "Rare Disease"],
  experiences: ["Testing Journey", "Doctor Visit", "Results", "Family", "Support"],
  education: ["Genetics 101", "DNA", "RNA", "CRISPR", "Bioinformatics", "Sequencing"],
  research: ["Papers", "Studies", "Datasets", "Open Science", "Tools"],
};

export function getCommunityTagOptions(communityName: string): string[] {
  const normalized = communityName.trim().toLowerCase();
  return COMMUNITY_TAG_OPTIONS_BY_CATEGORY[normalized] ?? GENERAL_COMMUNITY_TAG_OPTIONS;
}

