import { type MuscleGroup } from "./exercise-vocabulary.ts";

export const STANDARD_LIBRARY_TAG = "standard-library" as const;
export const STANDARD_LIBRARY_SOURCE = "wger" as const;

const EQUIPMENT_LABELS = {
  barbell: { en: "Barbell", es: "Barra" },
  bench: { en: "Bench", es: "Banco" },
  bodyweight: { en: "Bodyweight", es: "Peso corporal" },
  cable: { en: "Cable", es: "Polea" },
  dumbbell: { en: "Dumbbell", es: "Mancuerna" },
  kettlebell: { en: "Kettlebell", es: "Kettlebell" },
  machine: { en: "Machine", es: "Maquina" },
  medicine_ball: { en: "Medicine Ball", es: "Balon medicinal" },
  none: { en: "None", es: "Sin equipo" },
  pull_up_bar: { en: "Pull-up Bar", es: "Barra de dominadas" },
  discs: { en: "Discs", es: "Discos" },
  resistance_band: { en: "Resistance Band", es: "Banda elastica" },
  rope: { en: "Rope", es: "Cuerda" },
  smith: { en: "Smith", es: "Smith" },
  swiss_ball: { en: "Swiss Ball", es: "Pelota suiza" },
} as const;

type EquipmentKey = keyof typeof EQUIPMENT_LABELS;
type StandardBodyPart =
  | "CHEST"
  | "BACK"
  | "SHOULDERS"
  | "LEGS"
  | "GLUTES"
  | "HAMSTRINGS"
  | "QUADRICEPS"
  | "BICEPS"
  | "TRICEPS"
  | "FOREARMS"
  | "ABS"
  | "CORE"
  | "CALVES"
  | "FULL_BODY"
  | "CARDIO"
  | "FLEXIBILITY"
  | "ARMS";

interface FamilySpec {
  baseEn: string;
  baseEs: string;
  equipments: EquipmentKey[];
  aliases: string[];
  overview: string;
  bodyPart: StandardBodyPart;
  muscleGroups: MuscleGroup[];
  targetMuscles: string[];
  secondaryMuscles: string[];
  variations?: string[];
  /**
   * How the exercise is logged. Defaults to "reps". Set "time" for static holds
   * (stretches) and timed warm-ups that are logged by duration_seconds. Mirrors
   * the `metric` field consumed by exercise-schema.ts and the iOS/Android apps
   * (Phase 26). See issue #307.
   */
  metric?: "reps" | "time";
}

export interface StandardLibraryExercise {
  exerciseId: string;
  name: { en: string; es: string };
  bodyParts: StandardBodyPart[];
  equipment: EquipmentKey[];
  targetMuscles: string[];
  secondaryMuscles: string[];
  keywords: string[];
  variations: string[];
  overview: string;
  tags: string[];
  muscleGroups: MuscleGroup[];
  metric: "reps" | "time";
}

function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function uniq(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

function makeKeywords(baseEn: string, baseEs: string, equipment: EquipmentKey, aliases: string[]): string[] {
  const equipmentEn = EQUIPMENT_LABELS[equipment].en;
  const equipmentEs = EQUIPMENT_LABELS[equipment].es;
  return uniq([
    baseEn,
    baseEs,
    `${baseEn} ${equipmentEn}`,
    `${equipmentEn} ${baseEn}`,
    `${baseEs} ${equipmentEs}`,
    `${equipmentEs} ${baseEs}`,
    ...aliases,
  ]);
}

function makeExercise(groupSlug: string, family: FamilySpec, equipment: EquipmentKey): StandardLibraryExercise {
  const equipmentEn = EQUIPMENT_LABELS[equipment].en;
  const equipmentEs = EQUIPMENT_LABELS[equipment].es;
  const nameEn = `${family.baseEn} (${equipmentEn})`;
  const nameEs = `${family.baseEs} (${equipmentEs})`;
  return {
    exerciseId: `std-${groupSlug}-${slugify(family.baseEn)}-${slugify(equipmentEn)}`,
    name: { en: nameEn, es: nameEs },
    bodyParts: [family.bodyPart],
    equipment: [equipment],
    targetMuscles: family.targetMuscles,
    secondaryMuscles: family.secondaryMuscles,
    keywords: makeKeywords(family.baseEn, family.baseEs, equipment, family.aliases),
    variations: family.variations ?? [],
    overview: family.overview,
    tags: [STANDARD_LIBRARY_TAG],
    muscleGroups: family.muscleGroups,
    metric: family.metric ?? "reps",
  };
}

function family(input: FamilySpec): FamilySpec {
  return input;
}

const GROUPS: Array<{ slug: string; families: FamilySpec[] }> = [
  {
    slug: "chest",
    families: [
      family({
        baseEn: "Bench Press",
        baseEs: "Press de banca",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Flat Bench Press", "Chest Press", "Press de banca plano"],
        overview: "Standard horizontal press for chest strength.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "triceps", "shoulders"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Triceps brachii", "Anterior deltoid"],
        variations: ["Incline Bench Press", "Decline Bench Press", "Floor Press"],
      }),
      family({
        baseEn: "Incline Bench Press",
        baseEs: "Press de banca inclinado",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Incline Press", "Upper Chest Press"],
        overview: "Incline press variant emphasizing the upper chest.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "shoulders", "triceps"],
        targetMuscles: ["Pectoralis major clavicular head"],
        secondaryMuscles: ["Anterior deltoid", "Triceps brachii"],
        variations: ["Bench Press", "Decline Bench Press", "Low Incline Dumbbell Press"],
      }),
      family({
        baseEn: "Decline Bench Press",
        baseEs: "Press de banca declinado",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Decline Press", "Lower Chest Press"],
        overview: "Decline press variant emphasizing the lower chest.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "triceps"],
        targetMuscles: ["Pectoralis major sternal head"],
        secondaryMuscles: ["Triceps brachii", "Anterior deltoid"],
        variations: ["Bench Press", "Incline Bench Press", "Dumbbell Decline Press"],
      }),
      family({
        baseEn: "Chest Fly",
        baseEs: "Aperturas de pecho",
        equipments: ["dumbbell", "cable", "machine"],
        aliases: ["Dumbbell Fly", "Pec Fly", "Pec Deck"],
        overview: "Isolation movement for chest adduction and stretch.",
        bodyPart: "CHEST",
        muscleGroups: ["chest"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Anterior deltoid"],
        variations: ["Incline Chest Fly", "Cable Crossover", "Pec Deck Fly"],
      }),
      family({
        baseEn: "Cable Crossover",
        baseEs: "Cruce en polea",
        equipments: ["cable"],
        aliases: ["Standing Cable Fly", "Cable Fly"],
        overview: "Cable-based chest adduction with constant tension.",
        bodyPart: "CHEST",
        muscleGroups: ["chest"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Anterior deltoid"],
        variations: ["High Cable Crossover", "Low Cable Crossover", "Cable Fly"],
      }),
      family({
        baseEn: "Pec Deck Fly",
        baseEs: "Pec deck",
        equipments: ["machine"],
        aliases: ["Machine Fly", "Lever Pec Deck Fly"],
        overview: "Machine fly for stable chest isolation.",
        bodyPart: "CHEST",
        muscleGroups: ["chest"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Anterior deltoid"],
        variations: ["Chest Fly", "Cable Crossover"],
      }),
      family({
        baseEn: "Push-Up",
        baseEs: "Flexion de brazos",
        equipments: ["bodyweight"],
        aliases: ["Press-Up", "Bodyweight Push-Up"],
        overview: "Classic bodyweight press for chest and triceps.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "triceps", "core"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Triceps brachii", "Anterior deltoid", "Core"],
        variations: ["Incline Push-Up", "Decline Push-Up", "Diamond Push-Up"],
      }),
      family({
        baseEn: "Dip",
        baseEs: "Fondo",
        equipments: ["bodyweight", "machine"],
        aliases: ["Chest Dip", "Parallel Bar Dip"],
        overview: "Chest-focused dip with strong lower-chest and triceps demand.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "triceps", "shoulders"],
        targetMuscles: ["Pectoralis major", "Triceps brachii"],
        secondaryMuscles: ["Anterior deltoid"],
        variations: ["Assisted Dip", "Weighted Dip", "Bench Dip"],
      }),
      family({
        baseEn: "Floor Press",
        baseEs: "Press de suelo",
        equipments: ["barbell", "dumbbell", "smith"],
        aliases: ["Ground Press"],
        overview: "Press variation with shortened range of motion.",
        bodyPart: "CHEST",
        muscleGroups: ["chest", "triceps"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Triceps brachii", "Anterior deltoid"],
        variations: ["Bench Press", "Close Grip Floor Press"],
      }),
    ],
  },
  {
    slug: "back",
    families: [
      family({
        baseEn: "Pull-Up",
        baseEs: "Dominada",
        equipments: ["bodyweight", "pull_up_bar", "machine"],
        aliases: ["Wide Grip Pull-Up", "Assisted Pull-Up"],
        overview: "Vertical pull for lats and upper back.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps", "forearms"],
        targetMuscles: ["Latissimus dorsi"],
        secondaryMuscles: ["Biceps brachii", "Lower trapezius"],
        variations: ["Chin-Up", "Lat Pulldown", "Inverted Row"],
      }),
      family({
        baseEn: "Chin-Up",
        baseEs: "Dominada supina",
        equipments: ["bodyweight", "pull_up_bar", "machine"],
        aliases: ["Underhand Pull-Up", "Neutral Chin-Up"],
        overview: "Vertical pull with a supinated grip.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps", "forearms"],
        targetMuscles: ["Latissimus dorsi", "Biceps brachii"],
        secondaryMuscles: ["Rhomboids", "Lower trapezius"],
        variations: ["Pull-Up", "Assisted Chin-Up"],
      }),
      family({
        baseEn: "Lat Pulldown",
        baseEs: "Jalon al pecho",
        equipments: ["machine", "cable"],
        aliases: ["Wide Grip Lat Pulldown", "Pulldown"],
        overview: "Machine vertical pull when pull-ups are not the goal.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps"],
        targetMuscles: ["Latissimus dorsi"],
        secondaryMuscles: ["Biceps brachii", "Rhomboids"],
        variations: ["Close Grip Lat Pulldown", "Reverse Grip Pulldown"],
      }),
      family({
        baseEn: "Seated Row",
        baseEs: "Remo sentado",
        equipments: ["cable", "machine"],
        aliases: ["Cable Row", "Seated Cable Row"],
        overview: "Horizontal pull for lats and mid-back.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps"],
        targetMuscles: ["Latissimus dorsi", "Rhomboids"],
        secondaryMuscles: ["Biceps brachii", "Rear deltoid"],
        variations: ["Single-Arm Cable Row", "Chest-Supported Row"],
      }),
      family({
        baseEn: "Barbell Row",
        baseEs: "Remo con barra",
        equipments: ["barbell", "smith"],
        aliases: ["Bent Over Row", "Pendlay Row"],
        overview: "Heavy horizontal pull for back thickness.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps", "forearms"],
        targetMuscles: ["Latissimus dorsi", "Rhomboids", "Trapezius"],
        secondaryMuscles: ["Biceps brachii", "Erector spinae"],
        variations: ["T-Bar Row", "Seal Row"],
      }),
      family({
        baseEn: "Chest-Supported Row",
        baseEs: "Remo con soporte de pecho",
        equipments: ["machine", "dumbbell"],
        aliases: ["Incline Row", "Supported Row"],
        overview: "Supported row to reduce lower-back fatigue.",
        bodyPart: "BACK",
        muscleGroups: ["back", "biceps"],
        targetMuscles: ["Rhomboids", "Latissimus dorsi"],
        secondaryMuscles: ["Rear deltoid", "Biceps brachii"],
        variations: ["Seated Row", "T-Bar Row"],
      }),
      family({
        baseEn: "Face Pull",
        baseEs: "Jalon a la cara",
        equipments: ["cable", "rope"],
        aliases: ["Rope Face Pull", "Rear Delt Pull"],
        overview: "Upper-back and rear-delt accessory pull.",
        bodyPart: "BACK",
        muscleGroups: ["back", "shoulders"],
        targetMuscles: ["Rear deltoid", "Rhomboids"],
        secondaryMuscles: ["Lower trapezius", "Rotator cuff"],
        variations: ["Rear Delt Fly", "Cable High Row"],
      }),
      family({
        baseEn: "Straight-Arm Pulldown",
        baseEs: "Jalon con brazos rectos",
        equipments: ["cable"],
        aliases: ["Cable Pullover", "Lat Isolation Pulldown"],
        overview: "Lat isolation with elbows locked.",
        bodyPart: "BACK",
        muscleGroups: ["back", "core"],
        targetMuscles: ["Latissimus dorsi"],
        secondaryMuscles: ["Serratus anterior"],
        variations: ["Pullover", "Kneeling Straight-Arm Pulldown"],
      }),
      family({
        baseEn: "Deadlift",
        baseEs: "Peso muerto",
        equipments: ["barbell", "dumbbell", "smith"],
        aliases: ["Conventional Deadlift", "Hip Hinge"],
        overview: "Full posterior-chain pull and hinge pattern.",
        bodyPart: "BACK",
        muscleGroups: ["back", "glutes", "hamstrings", "legs"],
        targetMuscles: ["Erector spinae", "Glutes", "Hamstrings"],
        secondaryMuscles: ["Forearms", "Trapezius"],
        variations: ["Romanian Deadlift", "Rack Pull", "Sumo Deadlift"],
      }),
    ],
  },
  {
    slug: "shoulders",
    families: [
      family({
        baseEn: "Military Standing Press",
        baseEs: "Press militar de pie",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Shoulder Press", "Overhead Press", "Standing Press"],
        overview: "Classic overhead press for delts and triceps.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "triceps", "core"],
        targetMuscles: ["Anterior deltoid", "Medial deltoid"],
        secondaryMuscles: ["Triceps brachii", "Upper chest"],
        variations: ["Seated Shoulder Press", "Push Press"],
      }),
      family({
        baseEn: "Seated Shoulder Press",
        baseEs: "Press de hombros sentado",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Seated Overhead Press", "Seated Press"],
        overview: "Stable pressing pattern with less lower-body demand.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "triceps"],
        targetMuscles: ["Anterior deltoid", "Medial deltoid"],
        secondaryMuscles: ["Triceps brachii"],
        variations: ["Military Standing Press", "Arnold Press"],
      }),
      family({
        baseEn: "Arnold Press",
        baseEs: "Press Arnold",
        equipments: ["dumbbell"],
        aliases: ["Rotational Press"],
        overview: "Rotational dumbbell press for full delt development.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "triceps"],
        targetMuscles: ["Anterior deltoid", "Medial deltoid"],
        secondaryMuscles: ["Triceps brachii"],
        variations: ["Seated Shoulder Press", "Dumbbell Shoulder Press"],
      }),
      family({
        baseEn: "Lateral Raise",
        baseEs: "Elevacion lateral",
        equipments: ["dumbbell", "cable", "machine"],
        aliases: ["Side Raise", "Delt Raise"],
        overview: "Medial-delt isolation staple.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders"],
        targetMuscles: ["Medial deltoid"],
        secondaryMuscles: ["Upper trapezius"],
        variations: ["Cable Lateral Raise", "Machine Lateral Raise"],
      }),
      family({
        baseEn: "Front Raise",
        baseEs: "Elevacion frontal",
        equipments: ["dumbbell", "discs", "cable"],
        aliases: ["Plate Raise", "Front Delt Raise"],
        overview: "Anterior-delt accessory lift.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders"],
        targetMuscles: ["Anterior deltoid"],
        secondaryMuscles: ["Upper chest"],
        variations: ["Cable Front Raise", "Plate Front Raise"],
      }),
      family({
        baseEn: "Rear Delt Fly",
        baseEs: "Apertura posterior",
        equipments: ["dumbbell", "cable", "machine"],
        aliases: ["Reverse Fly", "Rear Fly"],
        overview: "Isolation work for rear delts and upper back.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "back"],
        targetMuscles: ["Posterior deltoid"],
        secondaryMuscles: ["Rhomboids", "Mid trapezius"],
        variations: ["Face Pull", "Cable Reverse Fly"],
      }),
      family({
        baseEn: "Push Press",
        baseEs: "Push press",
        equipments: ["barbell", "dumbbell"],
        aliases: ["Power Press"],
        overview: "Explosive overhead press with leg drive.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "legs", "triceps"],
        targetMuscles: ["Anterior deltoid", "Medial deltoid"],
        secondaryMuscles: ["Glutes", "Quadriceps", "Triceps brachii"],
        variations: ["Military Standing Press", "Jerk"],
      }),
      family({
        baseEn: "Upright Row",
        baseEs: "Remo al menton",
        equipments: ["barbell", "dumbbell", "cable"],
        aliases: ["High Pull Row"],
        overview: "Vertical pull that hits side delts and traps.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "back"],
        targetMuscles: ["Medial deltoid", "Upper trapezius"],
        secondaryMuscles: ["Biceps brachii"],
        variations: ["Cable Upright Row", "Dumbbell Upright Row"],
      }),
      family({
        baseEn: "Landmine Press",
        baseEs: "Press landmine",
        equipments: ["barbell"],
        aliases: ["Single-Arm Landmine Press", "Angle Press"],
        overview: "Shoulder press with a joint-friendly arc.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders", "core"],
        targetMuscles: ["Anterior deltoid", "Medial deltoid"],
        secondaryMuscles: ["Triceps brachii", "Core"],
        variations: ["Half-Kneeling Landmine Press", "Standing Landmine Press"],
      }),
    ],
  },
  {
    slug: "legs",
    families: [
      family({
        baseEn: "Back Squat",
        baseEs: "Sentadilla trasera",
        equipments: ["barbell", "smith", "machine"],
        aliases: ["High-Bar Squat", "Low-Bar Squat"],
        overview: "Foundational squat pattern for lower-body strength.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes", "hamstrings"],
        targetMuscles: ["Quadriceps", "Glutes"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Front Squat", "Pause Squat", "Box Squat"],
      }),
      family({
        baseEn: "Front Squat",
        baseEs: "Sentadilla frontal",
        equipments: ["barbell", "smith", "dumbbell"],
        aliases: ["Cross-Arm Front Squat", "Goblet Squat"],
        overview: "Quad-dominant squat with an upright torso.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "core"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Back Squat", "Goblet Squat"],
      }),
      family({
        baseEn: "Leg Press",
        baseEs: "Prensa de piernas",
        equipments: ["machine"],
        aliases: ["45 Degree Leg Press", "Horizontal Leg Press"],
        overview: "Machine-driven squat alternative.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        variations: ["Hack Squat", "Smith Squat"],
      }),
      family({
        baseEn: "Hack Squat",
        baseEs: "Sentadilla hack",
        equipments: ["machine", "smith"],
        aliases: ["Machine Squat"],
        overview: "Supported squat emphasizing quads.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes"],
        variations: ["Leg Press", "Front Squat"],
      }),
      family({
        baseEn: "Lunge",
        baseEs: "Zancada",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Walking Lunge", "Forward Lunge"],
        overview: "Unilateral lower-body staple.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes"],
        targetMuscles: ["Quadriceps", "Glutes"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Reverse Lunge", "Split Squat"],
      }),
      family({
        baseEn: "Split Squat",
        baseEs: "Sentadilla dividida",
        equipments: ["bodyweight", "dumbbell", "smith"],
        aliases: ["Stationary Lunge", "Bulgarian Split Squat"],
        overview: "Stationary unilateral quad and glute builder.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes"],
        targetMuscles: ["Quadriceps", "Glutes"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Bulgarian Split Squat", "Walking Lunge"],
      }),
      family({
        baseEn: "Step-Up",
        baseEs: "Subida al cajon",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Box Step-Up"],
        overview: "Single-leg drive with balance demand.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "glutes"],
        targetMuscles: ["Quadriceps", "Glutes"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Split Squat", "Lunge"],
      }),
      family({
        baseEn: "Leg Extension",
        baseEs: "Extension de piernas",
        equipments: ["machine"],
        aliases: ["Quad Extension"],
        overview: "Isolation movement for quadriceps.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: [],
        variations: ["Hack Squat", "Front Squat"],
      }),
      family({
        baseEn: "Leg Curl",
        baseEs: "Curl de piernas",
        equipments: ["machine"],
        aliases: ["Hamstring Curl"],
        overview: "Hamstring isolation on a machine.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Calves"],
        variations: ["Seated Leg Curl", "Lying Leg Curl"],
      }),
      family({
        baseEn: "Calf Raise",
        baseEs: "Elevacion de gemelos",
        equipments: ["machine", "smith", "bodyweight"],
        aliases: ["Standing Calf Raise", "Seated Calf Raise"],
        overview: "Calf strength and ankle stability.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Gastrocnemius", "Soleus"],
        secondaryMuscles: [],
        variations: ["Seated Calf Raise", "Donkey Calf Raise"],
      }),
    ],
  },
  {
    slug: "glutes",
    families: [
      family({
        baseEn: "Hip Thrust",
        baseEs: "Empuje de cadera",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Barbell Hip Thrust", "Glute Thrust"],
        overview: "Glute-dominant hip extension staple.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "hamstrings", "legs"],
        targetMuscles: ["Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Glute Bridge", "Single-Leg Hip Thrust"],
      }),
      family({
        baseEn: "Glute Bridge",
        baseEs: "Puente de gluteos",
        equipments: ["bodyweight", "barbell", "dumbbell", "smith"],
        aliases: ["Bridge", "Weighted Glute Bridge"],
        overview: "Floor-based glute bridge with easy load scaling.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "hamstrings", "core"],
        targetMuscles: ["Gluteus maximus"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Hip Thrust", "Single-Leg Glute Bridge"],
      }),
      family({
        baseEn: "Romanian Deadlift",
        baseEs: "Peso muerto rumano",
        equipments: ["barbell", "dumbbell", "smith"],
        aliases: ["RDL", "Stiff Leg Deadlift"],
        overview: "Hip hinge focused on glutes and hamstrings.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "hamstrings", "back"],
        targetMuscles: ["Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Erector spinae"],
        variations: ["Deadlift", "Single-Leg RDL"],
      }),
      family({
        baseEn: "Bulgarian Split Squat",
        baseEs: "Sentadilla bulgara",
        equipments: ["bodyweight", "dumbbell", "smith"],
        aliases: ["Rear Foot Elevated Split Squat", "RFESS"],
        overview: "Single-leg glute and quad builder.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "quadriceps", "legs"],
        targetMuscles: ["Gluteus maximus", "Quadriceps"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Split Squat", "Lunge"],
      }),
      family({
        baseEn: "Cable Kickback",
        baseEs: "Patada de gluteo en polea",
        equipments: ["cable"],
        aliases: ["Glute Kickback"],
        overview: "Glute isolation with cable resistance.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes"],
        targetMuscles: ["Gluteus maximus"],
        secondaryMuscles: [],
        variations: ["Machine Kickback", "Frog Pump"],
      }),
      family({
        baseEn: "Pull-Through",
        baseEs: "Jalon entre piernas",
        equipments: ["cable"],
        aliases: ["Cable Pull-Through", "Hip Hinge Pull-Through"],
        overview: "Cable hip hinge for posterior-chain endurance.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "hamstrings"],
        targetMuscles: ["Gluteus maximus", "Hamstrings"],
        secondaryMuscles: ["Core"],
        variations: ["Romanian Deadlift", "Kettlebell Swing"],
      }),
      family({
        baseEn: "Frog Pump",
        baseEs: "Puente rana",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Frog Bridge"],
        overview: "High-rep glute burner with short range.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes"],
        targetMuscles: ["Gluteus maximus"],
        secondaryMuscles: [],
        variations: ["Glute Bridge", "Hip Thrust"],
      }),
      family({
        baseEn: "Reverse Lunge",
        baseEs: "Zancada inversa",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Backward Lunge"],
        overview: "Lunge variation that keeps pressure on the glutes.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "quadriceps", "legs"],
        targetMuscles: ["Gluteus maximus", "Quadriceps"],
        secondaryMuscles: ["Hamstrings", "Core"],
        variations: ["Lunge", "Bulgarian Split Squat"],
      }),
    ],
  },
  {
    slug: "hamstrings",
    families: [
      family({
        baseEn: "Stiff-Leg Deadlift",
        baseEs: "Peso muerto piernas rigidas",
        equipments: ["barbell", "dumbbell", "smith"],
        aliases: ["Straight Leg Deadlift", "SLDL"],
        overview: "Hamstring-biased hinge with minimal knee bend.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings", "glutes", "back"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Erector spinae"],
        variations: ["Romanian Deadlift", "Deadlift"],
      }),
      family({
        baseEn: "Lying Leg Curl",
        baseEs: "Curl femoral tumbado",
        equipments: ["machine"],
        aliases: ["Prone Leg Curl"],
        overview: "Standard hamstring curl in the prone position.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Calves"],
        variations: ["Seated Leg Curl", "Leg Curl"],
      }),
      family({
        baseEn: "Seated Leg Curl",
        baseEs: "Curl femoral sentado",
        equipments: ["machine"],
        aliases: ["Hamstring Curl"],
        overview: "Seated curl emphasizing the hamstrings at length.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Calves"],
        variations: ["Lying Leg Curl", "Leg Curl"],
      }),
      family({
        baseEn: "Nordic Curl",
        baseEs: "Curl nordico",
        equipments: ["bodyweight", "bench"],
        aliases: ["Nordic Ham Curl"],
        overview: "High-intensity eccentric hamstring movement.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Glute Ham Raise", "Sliding Leg Curl"],
      }),
      family({
        baseEn: "Good Morning",
        baseEs: "Buenos dias",
        equipments: ["barbell", "smith"],
        aliases: ["Barbell Good Morning"],
        overview: "Hip hinge that loads the hamstrings heavily.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings", "glutes", "back"],
        targetMuscles: ["Hamstrings", "Glutes"],
        secondaryMuscles: ["Erector spinae"],
        variations: ["Stiff-Leg Deadlift", "Romanian Deadlift"],
      }),
      family({
        baseEn: "Single-Leg RDL",
        baseEs: "Peso muerto rumano a una pierna",
        equipments: ["dumbbell", "kettlebell", "barbell"],
        aliases: ["Single-Leg Romanian Deadlift"],
        overview: "Unilateral hinge for hamstrings and balance.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings", "glutes", "legs"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Romanian Deadlift", "Step-Up"],
      }),
      family({
        baseEn: "Glute Ham Raise",
        baseEs: "Elevacion de gluteo-femoral",
        equipments: ["machine", "bodyweight"],
        aliases: ["GHR", "Glute-Ham Developer"],
        overview: "Posterior-chain strength with strong hamstring demand.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings", "glutes"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Calves"],
        variations: ["Nordic Curl", "Lying Leg Curl"],
      }),
      family({
        baseEn: "Kettlebell Swing",
        baseEs: "Balanceo con kettlebell",
        equipments: ["kettlebell"],
        aliases: ["Russian Swing", "Hip Snap Swing"],
        overview: "Explosive hinge that trains the hamstrings dynamically.",
        bodyPart: "HAMSTRINGS",
        muscleGroups: ["hamstrings", "glutes", "core"],
        targetMuscles: ["Hamstrings", "Glutes"],
        secondaryMuscles: ["Core", "Forearms"],
        variations: ["Romanian Deadlift", "Deadlift"],
      }),
    ],
  },
  {
    slug: "quadriceps",
    families: [
      family({
        baseEn: "Leg Extension",
        baseEs: "Extension de piernas",
        equipments: ["machine"],
        aliases: ["Quad Extension"],
        overview: "Quadriceps isolation on a machine.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: [],
        variations: ["Front Squat", "Hack Squat"],
      }),
      family({
        baseEn: "Front Squat",
        baseEs: "Sentadilla frontal",
        equipments: ["barbell", "smith", "dumbbell"],
        aliases: ["Quad Squat", "Goblet Squat"],
        overview: "Upright squat pattern with a quad bias.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs", "core"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Back Squat", "Split Squat"],
      }),
      family({
        baseEn: "Hack Squat",
        baseEs: "Sentadilla hack",
        equipments: ["machine", "smith"],
        aliases: ["Machine Squat"],
        overview: "Supported squat for heavy quad loading.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes"],
        variations: ["Leg Press", "Front Squat"],
      }),
      family({
        baseEn: "Leg Press",
        baseEs: "Prensa de piernas",
        equipments: ["machine"],
        aliases: ["45 Degree Press"],
        overview: "Quad-focused press with stable torso support.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs", "glutes"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        variations: ["Hack Squat", "Split Squat"],
      }),
      family({
        baseEn: "Sissy Squat",
        baseEs: "Sentadilla sissy",
        equipments: ["bodyweight", "smith"],
        aliases: ["Bodyweight Sissy Squat"],
        overview: "High-knee-travel quad isolation pattern.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Core"],
        variations: ["Leg Extension", "Front Squat"],
      }),
      family({
        baseEn: "Walking Lunge",
        baseEs: "Zancada caminando",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Dynamic Lunge"],
        overview: "Quads and glutes with constant forward movement.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs", "glutes"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        variations: ["Reverse Lunge", "Split Squat"],
      }),
      family({
        baseEn: "Step-Up",
        baseEs: "Subida al cajon",
        equipments: ["bodyweight", "dumbbell", "barbell"],
        aliases: ["Box Step-Up"],
        overview: "Single-leg quad builder with knee drive.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "legs", "glutes"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Walking Lunge", "Split Squat"],
      }),
      family({
        baseEn: "Bulgarian Split Squat",
        baseEs: "Sentadilla bulgara",
        equipments: ["bodyweight", "dumbbell", "smith"],
        aliases: ["Rear Foot Elevated Split Squat"],
        overview: "Single-leg exercise that heavily loads the quads.",
        bodyPart: "QUADRICEPS",
        muscleGroups: ["quadriceps", "glutes", "legs"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Core"],
        variations: ["Split Squat", "Lunge"],
      }),
    ],
  },
  {
    slug: "biceps",
    families: [
      family({
        baseEn: "Barbell Curl",
        baseEs: "Curl con barra",
        equipments: ["barbell", "smith"],
        aliases: ["Standing Curl"],
        overview: "Classic biceps curl with a fixed grip.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps", "forearms"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Brachialis", "Forearms"],
        variations: ["EZ-Bar Curl", "Dumbbell Curl"],
      }),
      family({
        baseEn: "Dumbbell Curl",
        baseEs: "Curl con mancuerna",
        equipments: ["dumbbell", "cable"],
        aliases: ["Alternating Curl"],
        overview: "Flexible curl for arm symmetry and range.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps", "forearms"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Brachialis"],
        variations: ["Hammer Curl", "Incline Curl"],
      }),
      family({
        baseEn: "Hammer Curl",
        baseEs: "Curl martillo",
        equipments: ["dumbbell", "rope", "cable"],
        aliases: ["Neutral Grip Curl"],
        overview: "Neutral-grip curl for brachialis and forearms.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps", "forearms"],
        targetMuscles: ["Brachialis", "Biceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Cross-Body Hammer Curl", "Incline Hammer Curl"],
      }),
      family({
        baseEn: "Incline Curl",
        baseEs: "Curl inclinado",
        equipments: ["dumbbell"],
        aliases: ["Incline Dumbbell Curl"],
        overview: "Biceps curl performed on an incline bench.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Dumbbell Curl", "Preacher Curl"],
      }),
      family({
        baseEn: "Preacher Curl",
        baseEs: "Curl predicador",
        equipments: ["barbell", "dumbbell", "machine"],
        aliases: ["Scott Curl"],
        overview: "Supported curl that isolates the biceps.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Brachialis"],
        variations: ["Spider Curl", "Cable Curl"],
      }),
      family({
        baseEn: "Cable Curl",
        baseEs: "Curl en polea",
        equipments: ["cable"],
        aliases: ["High Cable Curl", "Bayesian Curl"],
        overview: "Constant-tension curl via cable stack.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Preacher Curl", "Dumbbell Curl"],
      }),
      family({
        baseEn: "Reverse Curl",
        baseEs: "Curl inverso",
        equipments: ["barbell", "dumbbell", "cable"],
        aliases: ["Pronated Curl"],
        overview: "Curl with a pronated grip for forearms and brachialis.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps", "forearms"],
        targetMuscles: ["Brachialis", "Forearms"],
        secondaryMuscles: ["Biceps brachii"],
        variations: ["Barbell Curl", "Hammer Curl"],
      }),
      family({
        baseEn: "Concentration Curl",
        baseEs: "Curl de concentracion",
        equipments: ["dumbbell"],
        aliases: ["Seated Concentration Curl"],
        overview: "Strict curl with maximal biceps focus.",
        bodyPart: "BICEPS",
        muscleGroups: ["biceps"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: [],
        variations: ["Preacher Curl", "Dumbbell Curl"],
      }),
    ],
  },
  {
    slug: "triceps",
    families: [
      family({
        baseEn: "Close Grip Bench Press",
        baseEs: "Press de banca agarre cerrado",
        equipments: ["barbell", "smith", "dumbbell"],
        aliases: ["Narrow Grip Bench Press"],
        overview: "Heavy triceps press with chest support.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps", "chest", "shoulders"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Pectoralis major", "Anterior deltoid"],
        variations: ["Floor Press", "Dips"],
      }),
      family({
        baseEn: "Pushdown",
        baseEs: "Extensiones en polea",
        equipments: ["cable", "rope"],
        aliases: ["Triceps Pushdown", "Rope Pushdown"],
        overview: "Cable triceps isolation with a stable torso.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: [],
        variations: ["Reverse-Grip Pushdown", "Single-Arm Pushdown"],
      }),
      family({
        baseEn: "Overhead Extension",
        baseEs: "Extension por encima de la cabeza",
        equipments: ["dumbbell", "cable", "machine"],
        aliases: ["Overhead Triceps Extension"],
        overview: "Triceps stretch and lockout pattern.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Core"],
        variations: ["French Press", "Rope Overhead Extension"],
      }),
      family({
        baseEn: "Skull Crusher",
        baseEs: "Rompecraneos",
        equipments: ["barbell", "dumbbell", "smith", "machine"],
        aliases: ["Lying Triceps Extension"],
        overview: "Elbow-extension isolation from a lying position.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Shoulders"],
        variations: ["Overhead Extension", "JM Press"],
      }),
      family({
        baseEn: "Dip",
        baseEs: "Fondo",
        equipments: ["bodyweight", "machine"],
        aliases: ["Triceps Dip", "Bench Dip"],
        overview: "Compound triceps movement with chest assist.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps", "chest", "shoulders"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Pectoralis major", "Anterior deltoid"],
        variations: ["Close Grip Bench Press", "Pushdown"],
      }),
      family({
        baseEn: "Kickback",
        baseEs: "Patada de triceps",
        equipments: ["dumbbell", "cable"],
        aliases: ["Cable Kickback"],
        overview: "Light isolation and squeeze for triceps finishers.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: [],
        variations: ["Overhead Extension", "Pushdown"],
      }),
      family({
        baseEn: "JM Press",
        baseEs: "JM press",
        equipments: ["barbell", "smith"],
        aliases: ["Close Grip Hybrid Press"],
        overview: "Hybrid press-extension for heavy triceps loading.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps", "chest"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Pectoralis major"],
        variations: ["Close Grip Bench Press", "Skull Crusher"],
      }),
      family({
        baseEn: "Bench Dip",
        baseEs: "Fondo en banco",
        equipments: ["bodyweight"],
        aliases: ["Bench Triceps Dip"],
        overview: "Simple bodyweight triceps movement.",
        bodyPart: "TRICEPS",
        muscleGroups: ["triceps", "chest"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Pectoralis major"],
        variations: ["Dip", "Close Grip Push-Up"],
      }),
    ],
  },
  {
    slug: "forearms",
    families: [
      family({
        baseEn: "Wrist Curl",
        baseEs: "Flexion de muñeca",
        equipments: ["barbell", "dumbbell", "cable"],
        aliases: ["Seated Wrist Curl"],
        overview: "Forearm flexor isolation.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms"],
        targetMuscles: ["Forearm flexors"],
        secondaryMuscles: [],
        variations: ["Reverse Wrist Curl", "Plate Pinch"],
      }),
      family({
        baseEn: "Reverse Wrist Curl",
        baseEs: "Flexion de muñeca inversa",
        equipments: ["barbell", "dumbbell", "cable"],
        aliases: ["Wrist Extension"],
        overview: "Forearm extensor isolation.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms"],
        targetMuscles: ["Forearm extensors"],
        secondaryMuscles: [],
        variations: ["Wrist Curl", "Reverse Curl"],
      }),
      family({
        baseEn: "Farmer Carry",
        baseEs: "Caminata del granjero",
        equipments: ["dumbbell", "kettlebell", "discs"],
        aliases: ["Suitcase Carry"],
        overview: "Loaded carry for grip and trunk stiffness.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms", "core", "shoulders"],
        targetMuscles: ["Grip", "Forearms"],
        secondaryMuscles: ["Core", "Upper traps"],
        variations: ["Suitcase Carry", "Rack Carry"],
      }),
      family({
        baseEn: "Dead Hang",
        baseEs: "Colgado pasivo",
        equipments: ["pull_up_bar"],
        aliases: ["Bar Hang"],
        overview: "Grip endurance on a bar.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms", "back"],
        targetMuscles: ["Grip"],
        secondaryMuscles: ["Lats"],
        variations: ["Towel Hang", "Active Hang"],
      }),
      family({
        baseEn: "Plate Pinch",
        baseEs: "Pinza de discos",
        equipments: ["discs"],
        aliases: ["Plate Pinch Hold"],
        overview: "Static grip challenge with discs.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms"],
        targetMuscles: ["Grip"],
        secondaryMuscles: [],
        variations: ["Farmer Carry", "Dead Hang"],
      }),
      family({
        baseEn: "Wrist Roller",
        baseEs: "Rulo de muñeca",
        equipments: ["barbell", "discs"],
        aliases: ["Forearm Roller"],
        overview: "Forearm endurance with repeated wrist flexion.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms"],
        targetMuscles: ["Forearms"],
        secondaryMuscles: [],
        variations: ["Wrist Curl", "Reverse Wrist Curl"],
      }),
      family({
        baseEn: "Pronation/Supination",
        baseEs: "Pronacion y supinacion",
        equipments: ["dumbbell"],
        aliases: ["Forearm Rotation"],
        overview: "Rotational forearm strength and control.",
        bodyPart: "FOREARMS",
        muscleGroups: ["forearms"],
        targetMuscles: ["Pronators", "Supinators"],
        secondaryMuscles: ["Grip"],
        variations: ["Wrist Curl", "Reverse Curl"],
      }),
    ],
  },
  {
    slug: "core",
    families: [
      family({
        baseEn: "Plank",
        baseEs: "Plancha",
        equipments: ["bodyweight", "swiss_ball"],
        aliases: ["Front Plank"],
        overview: "Foundational anti-extension core hold.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Rectus abdominis", "Transverse abdominis"],
        secondaryMuscles: ["Glutes", "Shoulders"],
        variations: ["Side Plank", "RKC Plank"],
      }),
      family({
        baseEn: "Side Plank",
        baseEs: "Plancha lateral",
        equipments: ["bodyweight", "swiss_ball"],
        aliases: ["Lateral Plank"],
        overview: "Anti-lateral-flexion trunk hold.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Obliques"],
        secondaryMuscles: ["Glutes", "Shoulders"],
        variations: ["Plank", "Copenhagen Side Plank"],
      }),
      family({
        baseEn: "Dead Bug",
        baseEs: "Bicho muerto",
        equipments: ["bodyweight", "medicine_ball"],
        aliases: ["Alternating Dead Bug"],
        overview: "Low-back friendly core coordination drill.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Transverse abdominis"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Bird Dog", "Hollow Hold"],
      }),
      family({
        baseEn: "Pallof Press",
        baseEs: "Press Pallof",
        equipments: ["cable", "resistance_band"],
        aliases: ["Anti-Rotation Press"],
        overview: "Anti-rotation core press.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Obliques", "Transverse abdominis"],
        secondaryMuscles: ["Glutes"],
        variations: ["Half-Kneeling Pallof Press", "Tall-Kneeling Pallof Press"],
      }),
      family({
        baseEn: "Ab Wheel",
        baseEs: "Rueda abdominal",
        equipments: ["none"],
        aliases: ["Rollout"],
        overview: "Hard anti-extension roll-out progression.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Lats", "Shoulders"],
        variations: ["Swiss Ball Rollout", "Plank"],
      }),
      family({
        baseEn: "Hollow Hold",
        baseEs: "Hollow body hold",
        equipments: ["bodyweight"],
        aliases: ["Hollow Body"],
        overview: "Gymnastic-style anti-extension hold.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Rectus abdominis", "Transverse abdominis"],
        secondaryMuscles: ["Hip flexors", "Shoulders"],
        variations: ["Dead Bug", "Plank"],
      }),
      family({
        baseEn: "Mountain Climber",
        baseEs: "Escalador",
        equipments: ["bodyweight"],
        aliases: ["Cross-Body Mountain Climber"],
        overview: "Dynamic core and conditioning drill.",
        bodyPart: "CORE",
        muscleGroups: ["core", "cardio"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Hip flexors", "Shoulders"],
        variations: ["High Knees", "Burpee"],
      }),
      family({
        baseEn: "Russian Twist",
        baseEs: "Giro ruso",
        equipments: ["bodyweight", "medicine_ball", "discs"],
        aliases: ["Seated Twist"],
        overview: "Rotational trunk control and oblique work.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Obliques"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Pallof Press", "Bicycle Crunch"],
      }),
    ],
  },
  {
    slug: "abs",
    families: [
      family({
        baseEn: "Crunch",
        baseEs: "Crunch abdominal",
        equipments: ["bodyweight", "machine"],
        aliases: ["Floor Crunch"],
        overview: "Classic spinal flexion ab move.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: [],
        variations: ["Sit-Up", "Reverse Crunch"],
      }),
      family({
        baseEn: "Reverse Crunch",
        baseEs: "Crunch inverso",
        equipments: ["bodyweight", "swiss_ball"],
        aliases: ["Hip Lift"],
        overview: "Lower-abs focused posterior pelvic tilt drill.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Crunch", "Leg Raise"],
      }),
      family({
        baseEn: "Leg Raise",
        baseEs: "Elevacion de piernas",
        equipments: ["bodyweight", "bench"],
        aliases: ["Hanging Leg Raise", "Lying Leg Raise"],
        overview: "Lower abdominal lift with strict control.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Reverse Crunch", "V-Up"],
      }),
      family({
        baseEn: "Bicycle Crunch",
        baseEs: "Crunch bicicleta",
        equipments: ["bodyweight"],
        aliases: ["Cross-Body Crunch"],
        overview: "Dynamic trunk rotation and ab flexion.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis", "Obliques"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Russian Twist", "Crunch"],
      }),
      family({
        baseEn: "Sit-Up",
        baseEs: "Abdominal sit-up",
        equipments: ["bodyweight", "medicine_ball", "discs"],
        aliases: ["Weighted Sit-Up"],
        overview: "Full-range trunk flexion.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Crunch", "V-Up"],
      }),
      family({
        baseEn: "V-Up",
        baseEs: "Elevacion en V",
        equipments: ["bodyweight"],
        aliases: ["Jackknife"],
        overview: "Advanced bodyweight abs movement.",
        bodyPart: "ABS",
        muscleGroups: ["abs", "core"],
        targetMuscles: ["Rectus abdominis"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Crunch", "Leg Raise"],
      }),
    ],
  },
  {
    slug: "calves",
    families: [
      family({
        baseEn: "Standing Calf Raise",
        baseEs: "Elevacion de gemelos de pie",
        equipments: ["machine", "smith", "bodyweight"],
        aliases: ["Calf Raise"],
        overview: "Classic standing calf movement.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Gastrocnemius"],
        secondaryMuscles: ["Soleus"],
        variations: ["Seated Calf Raise", "Donkey Calf Raise"],
      }),
      family({
        baseEn: "Seated Calf Raise",
        baseEs: "Elevacion de gemelos sentado",
        equipments: ["machine", "discs"],
        aliases: ["Bent-Knee Calf Raise"],
        overview: "Bent-knee calf work emphasizing the soleus.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Soleus"],
        secondaryMuscles: ["Gastrocnemius"],
        variations: ["Standing Calf Raise", "Leg Press Calf Raise"],
      }),
      family({
        baseEn: "Donkey Calf Raise",
        baseEs: "Elevacion de gemelos de burro",
        equipments: ["bodyweight", "machine"],
        aliases: ["Bent-Over Calf Raise"],
        overview: "Loaded calf work with a bent torso.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Gastrocnemius"],
        secondaryMuscles: ["Soleus"],
        variations: ["Standing Calf Raise", "Seated Calf Raise"],
      }),
      family({
        baseEn: "Leg Press Calf Raise",
        baseEs: "Gemelos en prensa",
        equipments: ["machine"],
        aliases: ["Calf Press"],
        overview: "Calf raise performed on the leg press platform.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Gastrocnemius", "Soleus"],
        secondaryMuscles: [],
        variations: ["Standing Calf Raise", "Seated Calf Raise"],
      }),
      family({
        baseEn: "Tibialis Raise",
        baseEs: "Elevacion tibial",
        equipments: ["bodyweight", "machine", "discs"],
        aliases: ["Tib Raise"],
        overview: "Anterior shin work for lower-leg balance.",
        bodyPart: "CALVES",
        muscleGroups: ["calves", "legs"],
        targetMuscles: ["Tibialis anterior"],
        secondaryMuscles: [],
        variations: ["Standing Calf Raise", "Jump Rope"],
      }),
    ],
  },
  {
    slug: "full_body",
    families: [
      family({
        baseEn: "Burpee",
        baseEs: "Burpee",
        equipments: ["bodyweight"],
        aliases: ["Squat Thrust"],
        overview: "Classic full-body conditioning drill.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "cardio", "legs", "core", "chest"],
        targetMuscles: ["Full body"],
        secondaryMuscles: [],
        variations: ["Squat Thrust", "Jump Squat"],
      }),
      family({
        baseEn: "Thruster",
        baseEs: "Thruster",
        equipments: ["barbell", "dumbbell", "kettlebell"],
        aliases: ["Squat to Press"],
        overview: "Squat plus overhead press for total-body power.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "legs", "shoulders", "triceps"],
        targetMuscles: ["Quadriceps", "Shoulders"],
        secondaryMuscles: ["Glutes", "Triceps"],
        variations: ["Push Press", "Clean and Press"],
      }),
      family({
        baseEn: "Kettlebell Swing",
        baseEs: "Balanceo con kettlebell",
        equipments: ["kettlebell"],
        aliases: ["Russian Swing"],
        overview: "Ballistic hinge for power and conditioning.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "hamstrings", "glutes", "core"],
        targetMuscles: ["Hamstrings", "Glutes"],
        secondaryMuscles: ["Core", "Forearms"],
        variations: ["Deadlift", "Burpee"],
      }),
      family({
        baseEn: "Turkish Get-Up",
        baseEs: "Levantamiento turco",
        equipments: ["kettlebell", "dumbbell"],
        aliases: ["Get-Up"],
        overview: "Full-body control and shoulder stability.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "shoulders", "core", "legs"],
        targetMuscles: ["Shoulders", "Core"],
        secondaryMuscles: ["Glutes", "Quadriceps"],
        variations: ["Windmill", "Overhead Carry"],
      }),
      family({
        baseEn: "Bear Crawl",
        baseEs: "Caminata de oso",
        equipments: ["bodyweight"],
        aliases: ["Quadruped Crawl"],
        overview: "Locomotion drill for shoulders, core, and legs.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "core", "shoulders", "legs"],
        targetMuscles: ["Core"],
        secondaryMuscles: ["Shoulders", "Quadriceps"],
        variations: ["Mountain Climber", "Plank"],
      }),
      family({
        baseEn: "Medicine Ball Slam",
        baseEs: "Golpe de balon medicinal",
        equipments: ["medicine_ball"],
        aliases: ["Ball Slam"],
        overview: "Explosive total-body conditioning throw.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "core", "shoulders", "legs"],
        targetMuscles: ["Core"],
        secondaryMuscles: ["Shoulders", "Glutes"],
        variations: ["Burpee", "Thruster"],
      }),
      family({
        baseEn: "Clean and Press",
        baseEs: "Clean y press",
        equipments: ["barbell", "dumbbell", "kettlebell"],
        aliases: ["Clean Press"],
        overview: "Power lift plus overhead press for full-body strength.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "legs", "shoulders", "triceps"],
        targetMuscles: ["Quadriceps", "Shoulders"],
        secondaryMuscles: ["Glutes", "Triceps"],
        variations: ["Thruster", "Push Press"],
      }),
    ],
  },
  {
    slug: "cardio",
    families: [
      family({
        baseEn: "Treadmill Run",
        baseEs: "Correr en cinta",
        equipments: ["machine"],
        aliases: ["Run", "Treadmill Jog"],
        overview: "Steady-state treadmill conditioning.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Legs"],
        variations: ["Sprint", "Incline Walk"],
      }),
      family({
        baseEn: "Rowing",
        baseEs: "Remo",
        equipments: ["machine"],
        aliases: ["Row Erg", "Rowing Machine"],
        overview: "Low-impact full-body cardio option.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "back", "legs", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Back", "Legs"],
        variations: ["Ski Erg", "Assault Bike"],
      }),
      family({
        baseEn: "Assault Bike",
        baseEs: "Bicicleta de aire",
        equipments: ["machine"],
        aliases: ["Air Bike", "Fan Bike"],
        overview: "High-output interval cardio machine.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Legs", "Shoulders"],
        variations: ["Rowing", "Ski Erg"],
      }),
      family({
        baseEn: "Jump Rope",
        baseEs: "Saltar la soga",
        equipments: ["rope"],
        aliases: ["Skipping Rope"],
        overview: "Simple conditioning drill with footwork demand.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "calves", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Calves"],
        variations: ["High Knees", "Burpee"],
      }),
      family({
        baseEn: "Stair Climber",
        baseEs: "Escaladora",
        equipments: ["machine"],
        aliases: ["StairMaster"],
        overview: "Step-based cardio with leg burn.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs", "glutes"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Glutes", "Quadriceps"],
        variations: ["Incline Walk", "Step-Up"],
      }),
      family({
        baseEn: "High Knees",
        baseEs: "Rodillas arriba",
        equipments: ["bodyweight"],
        aliases: ["Running in Place"],
        overview: "Fast-paced bodyweight conditioning drill.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs", "core"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Core", "Quadriceps"],
        variations: ["Jumping Jacks", "Mountain Climber"],
      }),
      family({
        baseEn: "Shadow Boxing",
        baseEs: "Boxeo sombra",
        equipments: ["bodyweight"],
        aliases: ["Air Boxing"],
        overview: "Upper-body cardio with rotational movement.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "shoulders", "core"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Shoulders", "Core"],
        variations: ["Jump Rope", "High Knees"],
      }),
      family({
        baseEn: "Sprint",
        baseEs: "Sprint",
        equipments: ["none"],
        aliases: ["Interval Run"],
        overview: "High-intensity speed conditioning.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        variations: ["Treadmill Run", "Shuttle Run"],
      }),
    ],
  },
  {
    slug: "flexibility",
    families: [
      family({
        baseEn: "Cat-Cow",
        baseEs: "Gato-vaca",
        equipments: ["bodyweight"],
        aliases: ["Spinal Mobility"],
        overview: "Gentle spinal mobility drill.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "core"],
        targetMuscles: ["Spine"],
        secondaryMuscles: ["Core"],
        variations: ["Thoracic Rotation", "Child's Pose"],
      }),
      family({
        baseEn: "Child's Pose",
        baseEs: "Postura del nino",
        equipments: ["bodyweight"],
        aliases: ["Extended Child's Pose"],
        overview: "Relaxing lat and spine stretch.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back"],
        targetMuscles: ["Lower back"],
        secondaryMuscles: ["Lats", "Shoulders"],
        variations: ["Cat-Cow", "Cobra Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Cobra Stretch",
        baseEs: "Estiramiento cobra",
        equipments: ["bodyweight"],
        aliases: ["Upward Dog Stretch"],
        overview: "Front-body opening and spinal extension.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "core"],
        targetMuscles: ["Abdominals"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Child's Pose", "Thoracic Rotation"],
        metric: "time",
      }),
      family({
        baseEn: "Pigeon Pose",
        baseEs: "Postura de la paloma",
        equipments: ["bodyweight"],
        aliases: ["Figure Four Stretch"],
        overview: "Hip external rotation and glute stretch.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "glutes"],
        targetMuscles: ["Glutes"],
        secondaryMuscles: ["Hip rotators"],
        variations: ["Hip Flexor Stretch", "Figure Four Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Hamstring Stretch",
        baseEs: "Estiramiento de isquiotibiales",
        equipments: ["bodyweight", "bench"],
        aliases: ["Seated Hamstring Stretch"],
        overview: "Classic posterior-chain flexibility drill.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Calves"],
        variations: ["Pigeon Pose", "Quad Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Quad Stretch",
        baseEs: "Estiramiento de cuadriceps",
        equipments: ["bodyweight"],
        aliases: ["Standing Quad Stretch"],
        overview: "Front-thigh flexibility drill.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "quadriceps"],
        targetMuscles: ["Quadriceps"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Hip Flexor Stretch", "Hamstring Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Chest Stretch",
        baseEs: "Estiramiento de pecho",
        equipments: ["bodyweight", "bench"],
        aliases: ["Doorway Chest Stretch"],
        overview: "Pectoral opening stretch.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "chest"],
        targetMuscles: ["Pectoralis major"],
        secondaryMuscles: ["Anterior deltoid"],
        variations: ["Shoulder Stretch", "Thoracic Rotation"],
        metric: "time",
      }),
      family({
        baseEn: "Thoracic Rotation",
        baseEs: "Rotacion toracica",
        equipments: ["bodyweight"],
        aliases: ["Open Book"],
        overview: "Upper-back mobility rotation drill.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back", "core"],
        targetMuscles: ["Thoracic spine"],
        secondaryMuscles: ["Shoulders", "Core"],
        variations: ["Cat-Cow", "Child's Pose"],
      }),
      family({
        baseEn: "Full Body Stretch",
        baseEs: "Estiramiento de cuerpo completo",
        equipments: ["bodyweight"],
        aliases: ["Total Body Stretch", "Cooldown Stretch"],
        overview: "General head-to-toe cooldown stretch routine.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "full_body"],
        targetMuscles: ["Full body"],
        secondaryMuscles: [],
        variations: ["Standing Lateral Stretch", "Spine Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Rear Deltoid Stretch",
        baseEs: "Estiramiento de deltoides posterior",
        equipments: ["bodyweight"],
        aliases: ["Cross-Body Shoulder Stretch", "Posterior Shoulder Stretch"],
        overview: "Cross-body stretch for the rear shoulder.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "shoulders"],
        targetMuscles: ["Posterior deltoid"],
        secondaryMuscles: ["Rotator cuff"],
        variations: ["Chest Stretch", "Triceps Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Triceps Stretch",
        baseEs: "Estiramiento de triceps",
        equipments: ["bodyweight"],
        aliases: ["Overhead Arm Stretch"],
        overview: "Overhead stretch for the triceps and lats.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Lats"],
        variations: ["Overhead Triceps Stretch", "Rear Deltoid Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Overhead Triceps Stretch",
        baseEs: "Estiramiento de triceps sobre la cabeza",
        equipments: ["bodyweight"],
        aliases: ["Behind-the-Head Triceps Stretch"],
        overview: "Bent-elbow overhead reach for triceps length.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Shoulders"],
        variations: ["Triceps Stretch", "Rear Deltoid Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Neck Side Stretch",
        baseEs: "Estiramiento lateral de cuello",
        equipments: ["bodyweight"],
        aliases: ["Lateral Neck Stretch"],
        overview: "Gentle side bend stretch for the neck.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility"],
        targetMuscles: ["Neck"],
        secondaryMuscles: ["Trapezius"],
        variations: ["Upper Back Stretch", "Standing Lateral Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Seated Glute Stretch",
        baseEs: "Estiramiento de gluteos sentado",
        equipments: ["bodyweight"],
        aliases: ["Figure Four Stretch", "Seated Pigeon"],
        overview: "Seated figure-four stretch for the glutes.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "glutes"],
        targetMuscles: ["Glutes"],
        secondaryMuscles: ["Hip rotators"],
        variations: ["Pigeon Pose", "Seated Piriformis Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Seated Piriformis Stretch",
        baseEs: "Estiramiento de piriforme sentado",
        equipments: ["bodyweight"],
        aliases: ["Piriformis Stretch"],
        overview: "Targeted stretch for the piriformis and deep hip.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "glutes"],
        targetMuscles: ["Piriformis"],
        secondaryMuscles: ["Glutes"],
        variations: ["Seated Glute Stretch", "Pigeon Pose"],
        metric: "time",
      }),
      family({
        baseEn: "Runners Stretch",
        baseEs: "Estiramiento del corredor",
        equipments: ["bodyweight"],
        aliases: ["Runner's Lunge Stretch", "Low Lunge Stretch"],
        overview: "Deep lunge stretch for hips and hamstrings.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "hamstrings", "glutes"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Hip flexors", "Glutes"],
        variations: ["Hamstring Stretch", "World's Greatest Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Calf Stretch",
        baseEs: "Estiramiento de pantorrilla",
        equipments: ["bodyweight"],
        aliases: ["Standing Calf Stretch", "Wall Calf Stretch"],
        overview: "Standing wall stretch for the calves.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "calves"],
        targetMuscles: ["Gastrocnemius"],
        secondaryMuscles: ["Soleus"],
        variations: ["Hamstring Stretch", "Quad Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Kneeling Lat Stretch",
        baseEs: "Estiramiento de dorsales arrodillado",
        equipments: ["bodyweight"],
        aliases: ["Puppy Pose", "Lat Stretch"],
        overview: "Kneeling reach to lengthen the lats and spine.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back"],
        targetMuscles: ["Lats"],
        secondaryMuscles: ["Shoulders", "Spine"],
        variations: ["Child's Pose", "Upper Back Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Spine Stretch",
        baseEs: "Estiramiento de columna",
        equipments: ["bodyweight"],
        aliases: ["Seated Forward Fold", "Spinal Stretch"],
        overview: "Seated forward reach to decompress the spine.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back"],
        targetMuscles: ["Spine"],
        secondaryMuscles: ["Hamstrings"],
        variations: ["Upper Back Stretch", "Seated Lower Back Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Upper Back Stretch",
        baseEs: "Estiramiento de espalda alta",
        equipments: ["bodyweight"],
        aliases: ["Thoracic Stretch", "Round Back Stretch"],
        overview: "Rounded reach stretch for the upper back.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back"],
        targetMuscles: ["Upper back"],
        secondaryMuscles: ["Rhomboids", "Shoulders"],
        variations: ["Spine Stretch", "Kneeling Lat Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Seated Lower Back Stretch",
        baseEs: "Estiramiento de espalda baja sentado",
        equipments: ["bodyweight"],
        aliases: ["Seated Twist Stretch", "Lower Back Stretch"],
        overview: "Seated rotation stretch for the lower back.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "back"],
        targetMuscles: ["Lower back"],
        secondaryMuscles: ["Glutes", "Obliques"],
        variations: ["Spine Stretch", "Child's Pose"],
        metric: "time",
      }),
      family({
        baseEn: "Standing Lateral Stretch",
        baseEs: "Estiramiento lateral de pie",
        equipments: ["bodyweight"],
        aliases: ["Side Reach Stretch", "Standing Side Stretch"],
        overview: "Overhead side bend to stretch the obliques and lats.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "core", "back"],
        targetMuscles: ["Obliques"],
        secondaryMuscles: ["Lats"],
        variations: ["Spine Stretch", "Upper Back Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Butterfly Stretch",
        baseEs: "Estiramiento de mariposa",
        equipments: ["bodyweight"],
        aliases: ["Butterfly Yoga Pose", "Groin Stretch"],
        overview: "Seated stretch for the inner thighs and hips.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "legs", "glutes"],
        targetMuscles: ["Adductors"],
        secondaryMuscles: ["Hip flexors"],
        variations: ["Pigeon Pose", "Seated Glute Stretch"],
        metric: "time",
      }),
      family({
        baseEn: "Side Wrist Stretch",
        baseEs: "Estiramiento lateral de muneca",
        equipments: ["bodyweight"],
        aliases: ["Wrist Pull Stretch", "Forearm Stretch"],
        overview: "Pulling stretch for the wrist and forearm.",
        bodyPart: "FLEXIBILITY",
        muscleGroups: ["flexibility", "forearms"],
        targetMuscles: ["Forearms"],
        secondaryMuscles: ["Wrist flexors"],
        variations: ["Triceps Stretch", "Rear Deltoid Stretch"],
        metric: "time",
      }),
    ],
  },
  {
    slug: "warmup",
    families: [
      family({
        baseEn: "General Warm-up",
        baseEs: "Calentamiento general",
        equipments: ["none"],
        aliases: ["Full Body Warm-up", "Dynamic Warm-up"],
        overview: "General full-body warm-up to raise core temperature.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "cardio"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: [],
        variations: ["Cardio Warm-up", "Jumping Jacks"],
        metric: "time",
      }),
      family({
        baseEn: "Cardio Warm-up",
        baseEs: "Calentamiento cardiovascular",
        equipments: ["none"],
        aliases: ["Light Cardio", "Pulse Raiser"],
        overview: "Light cardio to elevate heart rate before training.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: [],
        variations: ["General Warm-up", "Jump Rope"],
        metric: "time",
      }),
      family({
        baseEn: "Jumping Jacks",
        baseEs: "Saltos de tijera",
        equipments: ["bodyweight"],
        aliases: ["Star Jumps"],
        overview: "Classic full-body warm-up jump.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Shoulders", "Calves"],
        variations: ["High Knees", "Jump Rope"],
        metric: "time",
      }),
      family({
        baseEn: "High Knees",
        baseEs: "Rodillas arriba",
        equipments: ["bodyweight"],
        aliases: ["Running in Place"],
        overview: "Fast knee-drive run-in-place warm-up.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "legs"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Hip flexors", "Quadriceps"],
        variations: ["Jumping Jacks", "Mountain Climber"],
        metric: "time",
      }),
      family({
        baseEn: "Mountain Climber",
        baseEs: "Escalador",
        equipments: ["bodyweight"],
        aliases: ["Running Plank"],
        overview: "Plank with alternating knee drives.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "core", "full_body"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Abdominals", "Shoulders"],
        variations: ["High Knees", "Jumping Jacks"],
        metric: "time",
      }),
      family({
        baseEn: "Jump Rope",
        baseEs: "Saltar la cuerda",
        equipments: ["rope"],
        aliases: ["Skipping"],
        overview: "Rope skipping for a cardio warm-up.",
        bodyPart: "CARDIO",
        muscleGroups: ["cardio", "calves"],
        targetMuscles: ["Cardiorespiratory system"],
        secondaryMuscles: ["Calves", "Forearms"],
        variations: ["Jumping Jacks", "High Knees"],
        metric: "time",
      }),
      family({
        baseEn: "Inchworm",
        baseEs: "Oruga",
        equipments: ["bodyweight"],
        aliases: ["Walk-Out"],
        overview: "Walk-out drill mobilizing hamstrings and core.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "core", "hamstrings"],
        targetMuscles: ["Hamstrings"],
        secondaryMuscles: ["Abdominals", "Shoulders"],
        variations: ["World's Greatest Stretch", "Mountain Climber"],
        metric: "reps",
      }),
      family({
        baseEn: "World's Greatest Stretch",
        baseEs: "El mejor estiramiento del mundo",
        equipments: ["bodyweight"],
        aliases: ["Lunge with Rotation"],
        overview: "Multi-joint mobility drill for the whole body.",
        bodyPart: "FULL_BODY",
        muscleGroups: ["full_body", "hamstrings", "glutes"],
        targetMuscles: ["Hip flexors"],
        secondaryMuscles: ["Hamstrings", "Thoracic spine"],
        variations: ["Inchworm", "Runners Stretch"],
        metric: "reps",
      }),
      family({
        baseEn: "Glute Bridge March",
        baseEs: "Puente de gluteos con marcha",
        equipments: ["bodyweight"],
        aliases: ["Marching Glute Bridge"],
        overview: "Glute activation drill with alternating leg march.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "core"],
        targetMuscles: ["Glutes"],
        secondaryMuscles: ["Hamstrings", "Abdominals"],
        variations: ["Glute Bridge", "Hip Thrust"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Shoulders",
        baseEs: "Calentamiento de hombros",
        equipments: ["bodyweight"],
        aliases: ["Shoulder Mobility", "Arm Circles"],
        overview: "Light mobility drills to prepare the shoulders.",
        bodyPart: "SHOULDERS",
        muscleGroups: ["shoulders"],
        targetMuscles: ["Deltoids"],
        secondaryMuscles: ["Rotator cuff"],
        variations: ["Warm-up Arms", "Rear Deltoid Stretch"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Legs",
        baseEs: "Calentamiento de piernas",
        equipments: ["bodyweight"],
        aliases: ["Leg Swings", "Leg Mobility"],
        overview: "Light mobility drills to prepare the legs.",
        bodyPart: "LEGS",
        muscleGroups: ["legs", "quadriceps", "hamstrings"],
        targetMuscles: ["Quadriceps", "Hamstrings"],
        secondaryMuscles: ["Glutes", "Calves"],
        variations: ["Warm-up Hips", "High Knees"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Hips",
        baseEs: "Calentamiento de cadera",
        equipments: ["bodyweight"],
        aliases: ["Hip Circles", "Hip Mobility"],
        overview: "Light mobility drills to prepare the hips.",
        bodyPart: "GLUTES",
        muscleGroups: ["glutes", "legs"],
        targetMuscles: ["Glutes", "Hip flexors"],
        secondaryMuscles: ["Adductors"],
        variations: ["Warm-up Legs", "World's Greatest Stretch"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Back",
        baseEs: "Calentamiento de espalda",
        equipments: ["bodyweight"],
        aliases: ["Back Mobility", "Scapular Activation"],
        overview: "Light mobility drills to prepare the back.",
        bodyPart: "BACK",
        muscleGroups: ["back"],
        targetMuscles: ["Lats"],
        secondaryMuscles: ["Rhomboids", "Trapezius"],
        variations: ["Warm-up Shoulders", "Cat-Cow"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Arms",
        baseEs: "Calentamiento de brazos",
        equipments: ["bodyweight"],
        aliases: ["Arm Mobility", "Wrist Circles"],
        overview: "Light mobility drills to prepare the arms and wrists.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "biceps", "triceps"],
        targetMuscles: ["Biceps brachii", "Triceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Warm-up Shoulders", "Side Wrist Stretch"],
        metric: "reps",
      }),
      family({
        baseEn: "Warm-up Core",
        baseEs: "Calentamiento de core",
        equipments: ["bodyweight"],
        aliases: ["Core Activation", "Trunk Mobility"],
        overview: "Light activation drills to prepare the core.",
        bodyPart: "CORE",
        muscleGroups: ["core", "abs"],
        targetMuscles: ["Abdominals"],
        secondaryMuscles: ["Obliques", "Lower back"],
        variations: ["Mountain Climber", "Glute Bridge March"],
        metric: "reps",
      }),
    ],
  },
  {
    slug: "arms",
    families: [
      family({
        baseEn: "Arm Curl",
        baseEs: "Curl de brazos",
        equipments: ["dumbbell", "barbell", "cable"],
        aliases: ["Arm Builder Curl"],
        overview: "General arm-builder curl pattern.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "biceps"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Barbell Curl", "Hammer Curl"],
      }),
      family({
        baseEn: "Arm Extension",
        baseEs: "Extension de brazos",
        equipments: ["dumbbell", "cable", "machine"],
        aliases: ["Overhead Extension"],
        overview: "General arm-extension triceps pattern.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: [],
        variations: ["Pushdown", "Skull Crusher"],
      }),
      family({
        baseEn: "Close Grip Push-Up",
        baseEs: "Flexion cerrada",
        equipments: ["bodyweight"],
        aliases: ["Diamond Push-Up"],
        overview: "Bodyweight triceps and chest press.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "triceps", "chest"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: ["Pectoralis major"],
        variations: ["Push-Up", "Dip"],
      }),
      family({
        baseEn: "EZ-Bar Curl",
        baseEs: "Curl con barra EZ",
        equipments: ["barbell", "smith"],
        aliases: ["Spider Curl"],
        overview: "Wrist-friendly curl for biceps and forearms.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "biceps", "forearms"],
        targetMuscles: ["Biceps brachii"],
        secondaryMuscles: ["Brachialis", "Forearms"],
        variations: ["Barbell Curl", "Reverse Curl"],
      }),
      family({
        baseEn: "Rope Pushdown",
        baseEs: "Pushdown con cuerda",
        equipments: ["rope", "cable"],
        aliases: ["Triceps Rope Pushdown"],
        overview: "Arm accessory with strong triceps lockout.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "triceps"],
        targetMuscles: ["Triceps brachii"],
        secondaryMuscles: [],
        variations: ["Pushdown", "Overhead Extension"],
      }),
      family({
        baseEn: "Incline Hammer Curl",
        baseEs: "Curl martillo inclinado",
        equipments: ["dumbbell"],
        aliases: ["Incline Neutral Curl"],
        overview: "Long-length hammer curl for arm hypertrophy.",
        bodyPart: "ARMS",
        muscleGroups: ["arms", "biceps", "forearms"],
        targetMuscles: ["Brachialis", "Biceps brachii"],
        secondaryMuscles: ["Forearms"],
        variations: ["Hammer Curl", "Incline Curl"],
      }),
    ],
  },
];

function buildGroupExercises(spec: { slug: string; families: FamilySpec[] }): StandardLibraryExercise[] {
  return spec.families.flatMap((family) =>
    family.equipments.map((equipment) => makeExercise(spec.slug, family, equipment)),
  );
}

export const STANDARD_LIBRARY_EXERCISES: StandardLibraryExercise[] = GROUPS.flatMap(buildGroupExercises);

export function standardLibraryPreviewTitle(item: StandardLibraryExercise): string {
  return item.name.en;
}
